### ISSUE TITLE
How to connect to a Localhost Node?

### ISSUE THREAD

**Issue by johanazu7** [BANKEX/web3swift#1]
Hello,

Is it possible to connect to a Node running locally?
I've tried this but it does not work:

```
let url = URL(string: "http://localhost:8545")
let web3 = Web3.newWeb3(url) // returns nil
```
What's the procedure to achieve this? or do I have to deploy my contracts to **Rinkeby** network in order to do some testing?

Thank you.

**Comment by shamatar** [comment]
I've pushed a fix, plainly forgot to add initialization from custom URL even though HttpProvider was implemented for arbitrary URL. Please make sure that App Transport Security allows insecure (http) connections for your app.

**Comment by johanazu7** [comment]
I'll give it a shot! I had to resort to using Rinkeby in the meantime. Eager to see if your fix works, will report in a bit.
Thanks!

**Comment by CrisESC93** [comment]
Hello!

Sorry for open this issue again but I try to connect the web3 to my localhost but gives me nil. I'm using web3swift 0.2.10
