### ISSUE TITLE
sendERC20tokensWithNaturalUnits

### ISSUE THREAD

**Issue by jaramburu** [BANKEX/web3swift#100]
Hi Alex,

Will you update the version of web3+Eth.swift in the cocoapod to include the public function sendERC20tokensWithNaturalUnits? I am getting an error when I try to call this function.

**Comment by shamatar** [comment]
Yes, I’m working on 0.7.0 version with much improved event processing functionality, it will also include convenience functions for ERC20 transfers

________________________________

**Comment by shamatar** [comment]
Added in #101, that is a base for 0.7.0
