### ISSUE TITLE
The bug of change password

### ISSUE THREAD

**Issue by lviara** [BANKEX/web3swift#103]
<img width="1045" alt="2018-05-16 3 59 29" src="https://user-images.githubusercontent.com/15886470/40104157-2cba4230-5922-11e8-9cfb-d738e0db6616.png">

I enter the wrong oldpassword when change the keystore's password，the application crashes，"keyData" is nil
log:
Fatal error: Unexpectedly found nil while unwrapping an Optional value
it's in BIP32Keystore.swift and EthereumKeystoreV3.swift

**Comment by shamatar** [comment]
Hello @lviara 

Thank you for a feedback, will fix during the day. 

Sincerely, Alex

**Comment by shamatar** [comment]
Hello @lviara 

Should be fixed in #105 

Sincerely, Alex
