### ISSUE TITLE
enhancement - end to end newbie instructions to deploy erc20 token locally / initialize wallets - then successfully transfer it in app

### ISSUE THREAD

**Issue by johndpope** [BANKEX/web3swift#106]
jump start guide 
useful node scripts to deposit coins. initialize deposits.
https://github.com/izetex/contracts/tree/master/script

**Comment by johndpope** [comment]
there's a cool app called ganache for osx that rocks - I pasted some screen shots here.
https://github.com/izetex/contracts/issues/1

**Comment by johndpope** [comment]
also possible to use truffle console to interact with contract to do some pre steps. 
![screen shot 2018-05-16 at 15 18 49](https://user-images.githubusercontent.com/289994/40139023-837417aa-591c-11e8-8e6e-f4ce71c6893c.png)

**Comment by johndpope** [comment]
another way to fire up erc20 tokens could be a bash script 
https://github.com/johndpope/BabysittersClubDApp/blob/master/test/01_test1.sh

ideally - I'd like to interact with an erc721 token.

**Comment by johndpope** [comment]
we can use this - https://github.com/BANKEX/ERC20DividendsToken

**Comment by skywinder** [comment]
This issue was moved to matterinc/web3swift#89

**Comment by skywinder** [comment]
Hello. Me and Alex (@shamatar) as main maintainers are moving our development to the new repo.
➡️https://github.com/matterinc/web3swift ⬅️ 
Feel free continue discussion in the new repository. 👍 
Cheers.
