### ISSUE TITLE
Calling estimateGas() or a smart contract function via send() gives error: "gas required exceeds allowance or always failing transaction"

### ISSUE THREAD

**Issue by Kampeone** [BANKEX/web3swift#109]
I have this piece of code, trying to write some data to an array in my smart contract deployed on Rinkeby but i have this error: "nodeError: gas required exceeds allowance or always failing transaction ".

Also i have enough ethers in the test account so that shouldn't cause the issue.

Anyone had some similar issue and managed to solve it?

```
let web3Main = Web3.InfuraRinkebyWeb3()
let contract = web3Main.contract(contractABI, at: EthereumAddress("myContractAddress"))

let parameters = ["parameter1","parameter2"] as [AnyObject]
var options = Web3Options.defaultOptions() 
options.from = EthereumAddress("myAccountAddress")
      
 let myMethod = contract.method("myMethodName", parameters:parameters,  options: options)
 myMethod?.estimateGas(options: options, callback: { (result) in

     //gives error "gas required exceeds allowance or always failing transaction"
 })

 myMethod?.send(password: "myAccountPassword", options: options, callback: { (result) in

      //also gives error "gas required exceeds allowance or always failing transaction"
 })

```

**Comment by Kampeone** [comment]
I managed to fix the original error by setting gasLimit and gasPrice on the options variable.
But now the send method gives a "dataError".

**Comment by shamatar** [comment]
Hello @Kampeone 

Version 0.8 will bring much better gas limit management, in a meantime I’d recommend to first estimate a gas limit by calling “estimateGas”, and than supply this value in options. 

Sincerely, Alex
