### ISSUE TITLE
How to issuing the ERC20 token

### ISSUE THREAD

**Issue by lviara** [BANKEX/web3swift#110]
I want to do the function of issuing ERC20 token. Can you give me an example? thanks!!!

**Comment by shamatar** [comment]
Hello @lviara 

Please clarify your question. Do you need to call some function to issue tokens or do you want something else?

Sincerely, Alex

**Comment by lviara** [comment]
@shamatar 
Yes. I want to issue token. I find a example 'testDeployWithRemoteSigning' to deploy contract. But i don't known how to use it to issue token. Can you give me an example to issue token? thanks again

**Comment by shamatar** [comment]
@lviara 

Do you have a bytecode and an interface (ABI) of your smart-contract?

**Comment by lviara** [comment]
No. Aren't they generated by code? My colleague(Android) said they are generated by code. Used name、symbol、decimals and totalSupply

**Comment by shamatar** [comment]
Hello @lviara 

Creating a smart contract (eg. Solidity programming) is beyond the scope of this library issues. I suggest you to follow various documentations and tutorials for solidity programming. If you have a problem performing a transfer of ERC20 tokens please reopen.

Sincerely, Alex
