### ISSUE TITLE
How to get a list of the transactions of a Wallet address?

### ISSUE THREAD

**Issue by miguel-jimenez-0529** [BANKEX/web3swift#111]
I would like to know if there is a way to fetch the transactions for an specific wallet, and also is there a way to get a list of the transactions of ERC20 Tokens? 

I'm looking to get the results like etherscan shown in the image attached.

Regards,

![captura de pantalla 2018-05-22 a la s 11 24 18](https://user-images.githubusercontent.com/20710815/40375953-b4b07ada-5db2-11e8-88bc-1aea319d22e7.png)

**Comment by shamatar** [comment]
Hello @miguel-jimenez-0529 

Unfortunately such functionality requires to scan every transaction since origin for particular wallet. In principle you can do it from device for one wallet, but it’s very resource consuming.

Sincerely, Alex
