### ISSUE TITLE
support `web3.eth.Iban` api ? 

### ISSUE THREAD

**Issue by devSC** [BANKEX/web3swift#113]
hi. how to general address like the method of `web3.eth.Iban`?

**Comment by shamatar** [comment]
Hello @devSC 

Such feature is not yet implemented. I'll try to add it before 0.8 release, but without guarantees. Would you also send a request to #84 to have it listed?

Sincerely, Alex

**Comment by shamatar** [comment]
Would you update on master branch, it should be implemented after #115 as Web3.Utils.Iban It can take IBAN string like XE.... and generate Ethereum address from it. Non-standard (extra length) IBAN strings are not supported.

Sincerely, Alex

**Comment by shamatar** [comment]
Please reopen if functionality is not enough
