### ISSUE TITLE
Transfer ETH/Token return dataError

### ISSUE THREAD

**Issue by lviara** [BANKEX/web3swift#116]
Hello.
I transfor ETH/Token. The result is dataError. But My ETH/Token has been reduced.

**Comment by shamatar** [comment]
Hello @lviara 

Please refer to example and tests for a transfer procedures using either manual construction or convenience function. If you are on a "master" branch be sure to update to post #117 commits

Sincerely, Alex

**Comment by lviara** [comment]
@shamatar

Yes. it's normal after update.
