### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by myeveryheart** [BANKEX/web3swift#121]
The Swift pod `web3swift` depends upon `libsodium` and `secp256k1_ios`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by shamatar** [comment]
Hello @myeveryheart 

I'll look into this issue, thank you.

Sincerely, Alex

**Comment by shamatar** [comment]
@myeveryheart Would you try again with the latest version from "master"?

**Comment by myeveryheart** [comment]
@shamatar The latest version doesn't fix it. 
I  add
`
pod 'libsodium', :modular_headers => true
pod 'secp256k1_ios', :modular_headers => true
`
to the Podfile, then it works.

**Comment by myeveryheart** [comment]
@shamatar Hi, I think you should delete `use_frameworks!` and try again, since 

> With CocoaPods 1.5.0, developers are no longer restricted into specifying use_frameworks! in their Podfile in order to install pods that use Swift.

http://blog.cocoapods.org/CocoaPods-1.5.0/

**Comment by shamatar** [comment]
Looks like I need to add it to the podspec. I have those lines in a Podfile already

https://github.com/BANKEX/web3swift/blob/master/Podfile



________________________________

**Comment by shamatar** [comment]
@myeveryheart 

Would you try again from "master"?

**Comment by shamatar** [comment]
@myeveryheart 

Version 0.8.1 now defines modules as a part on configuration. If a problem still persists - feel free to reopen
