### ISSUE TITLE
set mnemonic for EthereumKeystoreV3

### ISSUE THREAD

**Issue by MrShafiee** [BANKEX/web3swift#122]
Hello.
How could we set mnemonic for EthereumKeystoreV3, because in your example we could set mnemonic for BIP32Keystore only.
What should I do if I want set mnemonic for EthereumKeystoreV3 too?
thanks.

**Comment by shamatar** [comment]
EthereumKeystoreV3 is not a HD wallet keystore, but rather a single key keystore, compatible with a format that Geth uses for private key storage. If you have some nonstandard way of generating single key keystore using a mnemonics, you can get seed from mnemonics using BIP39 class and form a private key from it somehow.

Sincerely, Alex
