### ISSUE TITLE
Watch Contract Events

### ISSUE THREAD

**Issue by junaidakram88** [BANKEX/web3swift#124]
Hi,

Can you please give me an example for watching the events from smart contract. So that, I'll refresh the details on event occurrence. 

event onContractCreateation(

        string name, 
        address employId
    ); 

function createContract(string _name, address _employId) public {

        EmployeeContract storage empContract = employeeContracts[_employId];
        empContract.name = _name;

        employeeContractsAccounts.push(_employId) -1;
        emit onContractCreateation(_name, _employId);
    }

**Comment by kilic** [comment]
Since swift implementation depends on a provider for example infura, you should frequently check if new events are emited between previous the `fromBlock` that should be updated in each filter and the `latest` .

```
let contract = web3.contract(jsonAbiString, at: nil/*contractAddress*/, abiVersion: 2)!
var filter = EventFilter()
filter.fromBlock = EventFilter.Block.blockNumber(previousBlockNumber)
filter.toBlock = latestBlockNumber//EventFilter.Block.latest
filter.addresses = [EthereumAddress("0x38e26a5bf585a8b72ab3319f3235595d0edd700d")!]
guard let eventResults = contract.getIndexedEvents(eventName: "SomeEvent", filter: filter) else {return}

switch eventResults {
case .success(let res):
    /*where you get events*/
    print(res)
case .failure(let error):
    print(error)
}

previousBlockNumber = latestBlockNumber
```

**Comment by shamatar** [comment]
@kilic Thanks for answering this 👍
