### ISSUE TITLE
Signing ERC20 transaction

### ISSUE THREAD

**Issue by Dubickiy** [BANKEX/web3swift#130]
Hi Guys

Could you please explain me how to just sign ERC20 transaction. I would like to get hex for sending tokens via RPC server by method **sendRawTransaction**. And parameter **Data** will be sent such as result of signing transaction

Thanks

**Comment by shamatar** [comment]
Hello @Dubickiy 

Sorry for a late response. There is no straightforward method for it, I hope to add it in 0.9. In a meantime if you want to locally sign a transaction and then send it to remote node (which is equivalent to sending a raw transaction), you can just initialize web3 with your node address as the provider, attach a keystore manager to web3 and use either convenience method like web3.eth.sendERC20....().send() or one of described in README for full contract initialization process

**Comment by Dubickiy** [comment]
@shamatar  thank you

I understood that. If you don't care, could you explain me one moment? I have generated hex and i should mention method "transfer" for transaction. I know that your library has method for that, but i want to understand how to generate it without methods.

Thanks 

Regards

**Comment by Mateo1999** [comment]
Hi @shamatar 
as you said :

> Sorry for a late response. There is no straightforward method for it, I hope to add it in 0.9. In a meantime if you want to locally sign a transaction and then send it to remote node (which is equivalent to sending a raw transaction), you can just initialize web3 with your node address as the provider, attach a keystore manager to web3 and use either convenience method like web3.eth.sendERC20....().send() or one of described in README for full contract initialization process

but I will receive this error 
> inputError("Failed to locally sign a transaction")

![photo_2018-07-03_17-26-47](https://user-images.githubusercontent.com/40632293/42221238-aed8afe2-7ee6-11e8-95f1-8b438a97f94c.jpg)

**Comment by shamatar** [comment]
You should supply a password in your ```.send()``` call

**Comment by Mateo1999** [comment]
👍 
thanks for reply
