### ISSUE TITLE
Account unlock

### ISSUE THREAD

**Issue by dmytronasyrov** [BANKEX/web3swift#141]
I'm using the library with Quorum. There is an issue with account unlock. Same
Note: gas price is 0 for Quorum, account created with BIP32 keystore.
Same request from Truffle works well. Any suggestions?

```
OPTIONS:  Web3Options(
  to: nil, 
  from: web3swift.EthereumAddress(_address: "0x6c9df56eb96ad78c7d0ea52213bd07afe8f00ec1",
  type: web3swift.EthereumAddress.AddressType.normal), 
  gasLimit: 4612388, 
  gasPrice: 0, 
  value: 0)

PROVIDER:  
http://127.0.0.1:22000 
web3swift.Networks.Custom(20)
[web3swift.EthereumAddress(_address:"0x6c9df56eb96ad78c7d0ea52213bd07afe8f00ec1", type: web3swift.EthereumAddress.AddressType.normal)]

REQUEST:  JSONRPCrequest(
  jsonrpc: "2.0",
  method: web3swift.JSONRPCmethod.unlockAccount, 
  params: Optional(web3swift.JSONRPCparams(params[
    "0x6c9df56eb96ad78c7d0ea52213bd07afe8f00ec1", 
    "", 
    300]
  )), 
  id: 5)

ERR:  Optional({
    error =     {
        code = "-32000";
        message = "no key for given address or file";
    };
    id = 5;
    jsonrpc = "2.0";
})
```

Truffle config:
```
networks: {
    KIM1: {
      host: "127.0.0.1",
      port: 22000,
      network_id: "20",
      gasPrice: 0,
      gas: 4612388
    }
  }
```

**Comment by shamatar** [comment]
Did you attach a keystore manager to your web3 instance? If you did - you do not need to a unlock account to send a transaction, because signing is done locally. Or do you need to unlock a remote one (on the remote node)?

________________________________

**Comment by dmytronasyrov** [comment]
Yes, but I get on `send(password, options)`
```
["id": 9, "error": {
    code = "-32000";
    message = "invalid sender";
}, "jsonrpc": 2.0]
```
I thought this can happen because account isn't unlocked.

```
Transaction
Nonce: 0
Gas price: 0
Gas limit: 3660254963
To: 0x7Fb03646fEa52Eec9aF5EF2DB3010DAf17AeB42D
Value: 0
Data: 0x60fe47b100000000000000000000000000000000000000000000000000000000000002c7
v: 76
r: 108059023212101560587794813621905669199545268290153343622615977154593493776222
s: 23336597767879217849193587189998531693945189509652803412007941437042898714017
Intrinsic chainID: Optional(20)
Infered chainID: Optional(20)
sender: Optional("0x4C1BeC157165e2eC8612edf9BA2F18DB2A4e11De")
hash: Optional("0xa7216096d41ba32184ad0428d7452796ab35329a25460ece2c50019a1b01bf6c")
```

**Comment by shamatar** [comment]
I’m not too familiar with Quorum but looks like the node doesn’t allow a locally singed transaction to be sent to network. Your “unlock account” request looks well formed, do you have a private key for this account on your Quorum node?

________________________________

**Comment by shamatar** [comment]
I’ve found a cross reference to https://github.com/ethers-io/ethers.js/issues/162 looks like Quorum doesn’t support EIP155 and you should set web3.network.chainID to nil

________________________________

**Comment by dmytronasyrov** [comment]
nillifying chainId works for this issue. But it looks like Quorum has much more things to setup to make it work as it should. Thanks.

**Comment by dmytronasyrov** [comment]
Latest version of Quorum supports EIP155 and there is no need to remove networkID. Everything works well.
