### ISSUE TITLE
set "aes-128-ctr" as parameters for encryptDataToStorage function

### ISSUE THREAD

**Issue by MrShafiee** [BANKEX/web3swift#146]
Hi @runryan, why did in encryptDataToStorage function on BIP32keystore.swift you set cipher : "aes-128-cbc" static! I want use it as "aes-128-ctr" and I should edit pod library! Can I sent it via parameters?

<img width="824" alt="41200871-c46723de-6cc1-11e8-9cc2-a675919f2cda" src="https://user-images.githubusercontent.com/19608549/41216713-ab90cdde-6d6a-11e8-8d11-6fe55577324a.png">

**Comment by shamatar** [comment]
Fixed in 0.9.0
