### ISSUE TITLE
how to call sendRawTransaction() It isn't available in code ??

### ISSUE THREAD

**Issue by Mahdimm** [BANKEX/web3swift#147]
hi @bankexgit thanks for you're awesome library I check out both you're sample and wallet. when I want to use this sendRawTransaction() function in web3 instance it isn't available how can I use this function to send signed transaction???

**Comment by dujinxin** [comment]
+1

**Comment by shamatar** [comment]
Hello everyone 

If you want to send a full transaction, you can do the following:
1) convert it to Data first (if you have a hex string)
2) use a parser EthereumTransaction.fromRaw(). Its failable, so you check for proper formatting of your transaction for free
3) send a parsed transaction using web3.eth.SendRawTransaction

I’ll put this feature in backlog, but not before 0.9 internal architecture rework.

Sincerely, Alex

**Comment by shamatar** [comment]
Fixed in 0.9.0

**Comment by shamatar** [comment]
Looks like I’ve forgotten to mark them as public :) sorry, will fix when get back to computer

________________________________

**Comment by MrShafiee** [comment]
Hi @shamatar Did you fix this issue? :)

**Comment by shamatar** [comment]
@MrShafiee 

Would you check a master branch after #169 PR?

Sincerely, Ale
