### ISSUE TITLE
Q: How to access public properties of the contract?

### ISSUE THREAD

**Issue by wingsofovnia** [BANKEX/web3swift#159]
There are a couple of public properties in my contract:
```
User[] public users;
uint public totalUsers = 0;
mapping (address => uint) public userDeviceCount;
```
I want to access them directly: `users` by index like `users[1]`, read `totalUsers` value and `userDeviceCount` by key, e.g. `userDeviceCount["0x123sdc123..."]`. Unfortunately I found no appropriate methods in `web3.web3contract`. I didn't find examples in tests or documentation how to do this.

Could someone please give an example how `users`, `totalUsers` and `userDeviceCount` can be accessed?

Thank you!

**Comment by shamatar** [comment]
@wingsofovnia 

Would you post your contract's ABI? Public parameters are just a syntax sugar and should be transformed to public getter functions.

Sincerely, Alex

**Comment by shamatar** [comment]
@wingsofovnia 

Please also list all methods in a contract: ```web3.web3contract.allMethods``` if I remember correctly

**Comment by wingsofovnia** [comment]
@shamatar 
here is an example contract with API.
https://gist.github.com/wingsofovnia/d0097918dd15ed5dc74ba7325f2651a8

**Comment by wingsofovnia** [comment]
It's not like I said something is not working it was rather a question how to access public fields, especially with an array. Thank you, the test shows that well now!

**Comment by shamatar** [comment]
I should have mentioned that public variables are transformed to getter functions with the corresponding number of input parameters (for mapping or arrays) and some output parameters (structures are flattened to arrays, for example, at least until solidity 0.5)
