### ISSUE TITLE
Password for every transaction

### ISSUE THREAD

**Issue by 6epreu** [BANKEX/web3swift#16]
Hello dev team.
Just wondering why you have decided to implement exactly this flow. Just now as I can see I need enter password every time when Im trying to send transaction. Inside sign transaction method I can see how the private key is getting.
F.e. in web3j java library I need only once unlock wallet ( enter password to get the private key) and I can sign as many transactions as I want. 
It's really annoying for user to ask him password every time.

**Comment by dsemenovsky** [comment]
Hi @6epreu !

In this case your workaround would be storing password somewhere else in your app, and them supplying the password variable each time you send a transaction.

It becomes your responsibility to clean up password when user logs out or quits application.

Best regards,
Dmitry

**Comment by shamatar** [comment]
Hello @6epreu 

Please see our reasoning and design decisions in updated Readme for 0.3.0 version.

Sincerely, Alex
