### ISSUE TITLE
address in the keystore 

### ISSUE THREAD

**Issue by dujinxin** [BANKEX/web3swift#160]
hi, the address in the imported keyStore does not have the prefix 0x ,that causes an error in the "sendETH..." function

> inputError("Failed to locally sign a transaction")

how could I solve this problem?

**Comment by shamatar** [comment]
Usually such error happens if you supply a wrong password. Please notice that your default password is not empty, it's "BANKEXFOUNDATION"

Sincerely, Alex

**Comment by shamatar** [comment]
@dujinxin 

It can also be related to a bug described in #163  , would you check the same behavior agains master branch after #164 commit

**Comment by dujinxin** [comment]
yeah,I will @shamatar ❤️
