### ISSUE TITLE
wrong validate on import wallet by keystone

### ISSUE THREAD

**Issue by MrShafiee** [BANKEX/web3swift#163]
Hi, 
I tried to import wallet by keystore JSON string, such as below json ; but I considered that when the wallet address is lowercase without x0 at the beginning of it, the process failed,  on the other hand when it has x0 at the beginning of it, import done successfully.

Keystore JSON sample:
{"address":"384f6cc........b8e74f9fb005c0c","id":"....","version":3,"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"76f7f74f68b.....8d8337f"},"ciphertext":"20047d2ba5c......c446d","kdf":"scrypt","kdfparams":{"dklen":32,"n":4096,"p":6,"r":8,"salt":"65eb801c.....154aa"},"mac":"43e97a0....31cd52"}}

when this function in EthereumAddress.swift file call internally, it return nil! 
```
public init?(_ addressString:String, type: AddressType = .normal, ignoreChecksum: Bool = false) {
        switch type {
        case .normal:
            guard let data = Data.fromHex(addressString) else {return nil}
            guard data.count == 20 else {return nil}
            if (!ignoreChecksum && data.toHexString().addHexPrefix() != addressString) {
                let checksummedAddress = EthereumAddress.toChecksumAddress(data.toHexString().addHexPrefix())
                guard checksummedAddress == addressString else {return nil}
            }
            self._address = data.toHexString().addHexPrefix()
            self.type = .normal
        case .contractDeployment:
            self._address = "0x"
            self.type = .contractDeployment
        }
    }
```

because at this line : 
      guard checksummedAddress == addressString else {return nil}

checksummedAddress is lower and upper letter with x0 and addressString is lowercase without x0.

what should I do to solve this problem?
tnx

**Comment by shamatar** [comment]
Hello @MrShafiee 

Would you check the same behavior agains master branch after #164 ?

Sincerely, Alex

**Comment by MrShafiee** [comment]
Hi @shamatar,
actually no, it's ( #160 ) about 7 hours ago; I will test it and inform you. 👍

**Comment by shamatar** [comment]
Great, closing :)
