### ISSUE TITLE
pod install fails on 0.8.0

### ISSUE THREAD

**Issue by James-Sangalli** [BANKEX/web3swift#166]
Hi All,

I am trying to download the pod but it fails with this: [!] CocoaPods could not find compatible versions for pod "Alamofire":
  In snapshot (Podfile.lock):
    Alamofire (= 4.6.0, ~> 4.1)

  In Podfile:
    Moya (~> 10.0.1) was resolved to 10.0.1, which depends on
      Moya/Core (= 10.0.1) was resolved to 10.0.1, which depends on
        Alamofire (~> 4.1)

    web3swift (~> 0.8.0) was resolved to 0.8.1, which depends on
      Alamofire (~> 4.7)

My iOS target is set to 9.0 and I have the latest version of xcode (These two reasons are the common cause already mentioned)

**Comment by shamatar** [comment]
Can you try to install 0.9.0?

I’ve updated an Example code with “pod update” command few days ago and didn’t encounter any issues.

________________________________

**Comment by James-Sangalli** [comment]
I have tried but still get this: 

[!] CocoaPods could not find compatible versions for pod "Result":
  In snapshot (Podfile.lock):
    Result (= 3.2.4, ~> 3.0, ~> 3.1)

  In Podfile:
    JSONRPCKit (from `https://github.com/bricklife/JSONRPCKit.git`) was resolved to 2.0.0, which depends on
      Result (~> 3.0)

    JavaScriptKit was resolved to 1.0.0, which depends on
      Result (~> 3.1)

    web3swift (~> 0.9.0) was resolved to 0.9.0, which depends on
      Result (~> 3.0.0)

**Comment by James-Sangalli** [comment]
Woop, we finally solved this but it was messy.
