### ISSUE TITLE
Recreate BIP32Keystore from private key only

### ISSUE THREAD

**Issue by adityasios** [BANKEX/web3swift#175]
Can is it possible to recreate BIP32Keystore from the private key only which i have got from UNSAFE_getPrivateKeyData(password: String, account: EthereumAddress) at the time keystore creation & stored.
I was able to recreate BIP32Keystore  from mnemonics & password but don't want to use the password to recreate it.

**Comment by shamatar** [comment]
Hello @adityasios 

You can not recreate a full BIP32Keystore from the private key - the BIP32 standard describes hierarchical derivation of the tree of keys, so having only one "leaf" is not enough to recreate a tree.

Sincerely, Alex
