### ISSUE TITLE
"Invalid input supplied" when getting balance of my ERC20 Token

### ISSUE THREAD

**Issue by GabCas** [BankEx/web3swift#176]
I followed the example at: [https://github.com/BANKEX/web3swift#getting-erc20-token-balance](url) and substituted the contract address and the ABI string with my own.  However, when calling the balanceOf method, I get this error:
![screen shot 2018-07-03 at 4 17 54 pm](https://user-images.githubusercontent.com/2333673/42242860-556f3592-7edd-11e8-97db-4e19cb1cf749.png)

Is there a way to determine the invalid input or additional information on why it failed?

PS. I'm able to get ETH balance without any issues

**Comment by shamatar** [comment]
Hello @GabCas 

An ABI and the contract address are necessary to replicate an issue. If you try to get erc20 token balance you do not need to change an abi by the way.

Sincerely, Alex

**Comment by GabCas** [comment]
Hi @shamatar,
 after getting the balance, I will attempt to call some custom methods of my token contract.  
You can test it on MainNet
Token Address is: 0x0f90969738c7a3088907c052cb96bd4d184a9fcf
You can find ABI here: https://api.etherscan.io/api?module=contract&action=getabi&address=0x0f90969738c7a3088907c052cb96bd4d184a9fcf
(the result property is the actual ABI, I ran it through a JSON escaper and seems to be formatted the same way as Web3.Utils.erc20ABI

I reproduced the error in my development blockchain and in the mainnet.

**Comment by shamatar** [comment]
Hello @GabCas 

I was able to get the balance, please check a function called testUserCase1() function in test of the latest version.

Sincerely, Alex

**Comment by shamatar** [comment]
Hm, I’ve tried to remove a mandatory “from” field for .call() method, looks like some form of a bug is still there

________________________________
