### ISSUE TITLE
"sender account not recognized" when calling contract set method

### ISSUE THREAD

**Issue by GabCas** [BANKEX/web3swift#182]
Hi,  
I'm calling a custom method of my contract but haven't been able to make it work.  Using `.send()` or `.send(password: "mywalletpassword")` results in a `nodeError("sender account not recognized")`

I also tried with: `.send(password: "mywalletpassword", options: options, onBlock: String(currentBlock) )` but that results in my private blockchain getting a time out.

Which is the correct way to call a set method in the blockchain?  I saw in the tests that the examples were deprecated.

Thanks,
Gab

**Comment by shamatar** [comment]
Do you try to sign a transaction locally and send it, or just want to rely on a remote node doing code signing?

obBlock can only take values “latest” and “pending”

________________________________

**Comment by GabCas** [comment]
@shamatar I'm assuming I want to sign the transaction locally.  For onBlock, I was using this code:
```
let blockNumber = web3Main?.eth.getBlockNumber()
guard case .success(let currentBlock)? = blockNumber else {return}
```
Would it be `onBlock: "latest"` ?  
I tried that and got "nodeError("sender account not recognized")"

**Comment by GabCas** [comment]
I tried that and got the same error.  I will attempt with another account as the account I'm trying right now was imported using: `let keystore = try! EthereumKeystoreV3(privateKey: pk!, password: "mywalletpassword")` and that pk might've not existed in the blockchain.  Will get back to you soon.

Thanks!

**Comment by GabCas** [comment]
@shamatar if I import an account from a private key like so:
`let keystore = try! EthereumKeystoreV3(privateKey: pk!, password: "password")`

that is the same password I would use in send(), like this right?
`let result = transactionIntermediate!.send(password: "password", options: options, onBlock: "latest" )`

Still getting error `nodeError("sender account not recognized")`
I am also setting:
```
var options = Web3Options.defaultOptions()
options.from = address
web3Main?.provider.network = nil
```

**Comment by shamatar** [comment]
Making a transaction is assembling a binary encoding, so address checksum doesn’t matter if you sing a transaction locally. I hope you did not forget to attach a keystore to a web3 object.

Yes, passwords should match, this part is fine, otherwise you would get different error.

Sincerely, Alex

________________________________

**Comment by GabCas** [comment]
Thanks @shamatar the issue must be that I'm not attaching the keystore to the web3 object.  Can you please direct me to the test that shows how to do this?  
Thanks!

**Comment by shamatar** [comment]
You just have to call web3.attachKeystore(someKeystore) and it will work. If you don’t attach it than your transactions will be sent to the remote node to be signed and relayed to network

**Comment by GabCas** [comment]
For the Web3 object, I only see addKeystoreManager.  
Regards

**Comment by shamatar** [comment]
Yes, that’s the one. You can check test of web3swift for a good part of examples

________________________________

**Comment by GabCas** [comment]
@shamatar I've added the keystore but it doesn't have the imported account.  I'm trying to add the imported account to my keystore but it seems that "keystores" is read only.  How can I add my imported keystore to the keystore manager?

![screen shot 2018-07-05 at 5 39 44 pm](https://user-images.githubusercontent.com/2333673/42349352-80b8e8e4-807a-11e8-85f2-0a8ec5b6b0b8.png)

Thanks again!

**Comment by shamatar** [comment]
`
            let tempKeystore = try! EthereumKeystoreV3(password: "")
            let keystoreManager = KeystoreManager([tempKeystore!])
            web3.addKeystoreManager(keystoreManager)
`

**Comment by GabCas** [comment]
Thanks. After creating the tempKeystore with the private key and password everything worked as expected.
