### ISSUE TITLE
Turning transaction debugging output on and off

### ISSUE THREAD

**Issue by abusse** [BANKEX/web3swift#186]
Currently, every transaction creates a debug output to the console (see e.g. `sendTransactionPromise`). This is good for early stage development, but gets annoying once you reach a point were you create several transaction not to say in production. So it would be nice to be able to turn the debugging output on and off or even better have a complete logging facility.

**Comment by shamatar** [comment]
Will do in 1.1, along with the documentation

**Comment by abusse** [comment]
Great, thank you!

**Comment by shamatar** [comment]
The latest version should have verbose messages disabled.
