### ISSUE TITLE
merge multi json rpc requests in one request

### ISSUE THREAD

**Issue by MrShafiee** [BANKEX/web3swift#187]
Hi @shamatar , when we transfer token you merge some request in on request, like this:
```
[{
	"jsonrpc": "2.0",
	"method": "eth_getTransactionCount",
	"id": 37,
	"params": ["0x0d13ab5ce239.....40b9bccb84af", "pending"]
}, {
	"jsonrpc": "2.0",
	"method": "eth_estimateGas",
	"id": 38,
	"params": [{
		"data": "0xa9059cbb000000000....e72a000",
		"to": "0x4f2a8a24197.....c42760d9bf9b6",
		"value": "0x0",
		"gasPrice": "0x0",
		"from": "0x0d13ab5ce239......71d40b9bccb84af"
	}]
}, {
	"jsonrpc": "2.0",
	"method": "eth_gasPrice",
	"id": 39,
	"params": []
}]
```

and get all response in on result such as this:
```
[{
	"jsonrpc": "2.0",
	"id": 37,
	"result": "0x1c"
}, {
	"jsonrpc": "2.0",
	"id": 38,
	"result": "0x8f2e"
}, {
	"jsonrpc": "2.0",
	"id": 39,
	"result": "0x4a817c800"
}]
```

How can I do this? for example I have some wallets and I want get balance of them, I could user getBalance function one by one and I should call server request 5-6 time, but I want send all of them in one request, what should I do ?

**Comment by shamatar** [comment]
Batching is done automatically under the hood, so if you use a single web3 object and try to check multiple balances, then all the requests will be batched

**Comment by Mahdimm** [comment]
hi @shamatar 
Can you explain it more? how it will be converted by it self or we should use some function for send multi Json rpc
thanks

**Comment by MrShafiee** [comment]
Hi @shamatar , I do that but web3 object will not batched request automatically under the hood, what should I do?
And this is my code:
```
let web3Provider = Web3.new(URL(string: "http://MYADDRESS")!)
        for wallet in listOfWallets {
            let balanceResult = web3Provider?.eth.getBalance(address: wallet.EthereumAddress!)
            guard case .success(let balance)? = balanceResult
            ....
            ....
        }
```

**Comment by shamatar** [comment]
Yeah, I should clarify a little.

Over the period of 0.1 second web3 object accumulates all RPC requests and then sends them to the remote node. To fully utilize it you should either use a promise based API or call synchronous functions (like one above) not in the main thread. Your code above is completely synchronous and waits for execution of the requests, so they are dispatched one by one.

Sincerely, Alex

________________________________

**Comment by ozibrahim** [comment]
Hi @shamatar , i have similar problem. I try to send only one request, library convert jsonrpc object to array, so i am getting error from remote node. Because remote node accepts only jsonrpc object.
Is that normal that web3swift convert to jsonrpc object to array even there is only one request?

Thanks,

**Comment by shamatar** [comment]
Hello @ozibrahim 

You can disable batching after creation of web3 object like the following:
```
        web3.requestDispatcher.policy = .NoBatching
```

I've based the default settings on the widespread nodes assumptions (Infura), so batching is on by default.

Sincerely, Alex
