### ISSUE TITLE
Interacting with custom smart contract using web3swift

### ISSUE THREAD

**Issue by mattgabor** [BANKEX/web3swift#188]
I am trying to interact with my own smart contract using web3swift in the following way using the example code (with items in <> replaced with actual values):
```swift
let myAddress = EthereumAddress(<myaddress>)!
let bytecode = Data.init(hex: <mybinary>)
        
let web3Rinkeby = Web3.InfuraRinkebyWeb3()
        
let gasPriceResult = web3Rinkeby.eth.getGasPrice()
guard case .success(let gasPrice) = gasPriceResult else {return}
        
var options = Web3Options.defaultOptions()
options.gasPrice = gasPrice
options.from = myAddress

let contract = web3Rinkeby.contract(<myabi>, at: nil, abiVersion: 2)
let intermediate = contract?.deploy(bytecode: bytecode, options: options)

let instance = intermediate?.call(options: options)
```

However, in the call to contract.deploy intermediate is nil. Any ideas?

**Comment by shamatar** [comment]
“Call” method references to an operation that tries to execute a function and get some return value. You should use either “send” or “estimateGas”

________________________________
