### ISSUE TITLE
Does this project support Object-c?

### ISSUE THREAD

**Issue by ddhjy** [BANKEX/web3swift#19]
Does this project support Object-c?

**Comment by skywinder** [comment]
Yes, like any other Swift projects.
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

Feel free to reopen the issue, if you still need help. 👍

**Comment by lifeshow** [comment]
你好，oc调用swift类的时候，对swift类要求是继承nsobject或者它的派生类，否则无法被oc发现或者调用失败，这个问题怎么处理？

**Comment by renhepeng** [comment]
> 你好，oc调用swift类的时候，对swift类要求是继承nsobject或者它的派生类，否则无法被oc发现或者调用失败，这个问题怎么处理？

解决了么？
