### ISSUE TITLE
Why does “Use of unresolved identifier” error occurs only for Device/Archive Builds?

### ISSUE THREAD

**Issue by CoderXuYB** [BANKEX/web3swift#190]
![snip20180718_5](https://user-images.githubusercontent.com/19338166/42882826-5c7392d4-8acc-11e8-8ddc-447782759bc2.png)

**Comment by shamatar** [comment]
You should not forget to set iOS or MacOS version in the Podfile when you install a library. There was such issue previously discussed.

**Comment by CoderXuYB** [comment]
@shamatar   I think I set the version. What should I do                  platform :ios, '10.0'
