### ISSUE TITLE
Great project with a little flaw

### ISSUE THREAD

**Issue by BillZong** [BANKEX/web3swift#191]
Ropsten testnet is not supported. So I forked it to make some local tests.

ps: My APP(Block Band) is using it, it'll be integrated within a few weeks. The APP was already provided in App Store. U could just add my APP onto the list afterwards.

**Comment by shamatar** [comment]
What exactly is not supported for Ropsten? I did not put a convenience initializer for Infura Ropsten servers, although you can always manually create it.

**Comment by BillZong** [comment]
OK, U’re right. XD
