### ISSUE TITLE
Crash: Fatal error: UnsafeMutablePointer.deinitialize with negative count

### ISSUE THREAD

**Issue by codesmirnov** [BANKEX/web3swift#193]
Hello!

I use web3swift 1.0.0

I got crash when I tried to send a transaction:

Promise+Batching.swift

line 49: ( self.requests.append(request) )

Fatal error: UnsafeMutablePointer.deinitialize with negative count

**Comment by shamatar** [comment]
Does this happen in debug or release build?

________________________________

**Comment by codesmirnov** [comment]
Not sure. But it seems on both.

**Comment by shamatar** [comment]
Can you disclose a workflow for reproduction purposes?

________________________________

**Comment by codesmirnov** [comment]
This happens sometimes when sending a single transaction.

Nothing special. 

Unfortunately there is no more info.

**Comment by shamatar** [comment]
Wow, that’s surprising. I’ll try to create some test for it

________________________________
