### ISSUE TITLE
Web3Error real description 

### ISSUE THREAD

**Issue by GabCas** [BankEx/web3swift#194]
Hi,

I'm having an issue with presenting the user the real description of a web3error.  For example:
`print(error) ` output: 

> nodeError("Attempting to run transaction which calls a contract function, but recipient address 0xf230b790e05390fc8295f4d3f60332c93bed42e2 is not a contract address")

`print(error.localizedDescription) ` output: 

> The operation couldn’t be completed. (web3swift.Web3Error error 1.)

I would like the user to know that the contract address is wrong instead of generic error 1.  This also happens when an error is thrown by gas, I'd like to tell the user to modify their gas price or gas limit instead of a generic error.  
Is this possible?
Thanks,

**Comment by shamatar** [comment]
Hello @GabCas 

Of course in can be done and such PR would be welcome. Errors are completely not structured at the moment and only indicate at what part of the workflow one has encountered it - either locally, when packing the data into the transaction, or it came from the remote node.

Sincerely, Alex
