### ISSUE TITLE
how to get mnemonic from privatekey

### ISSUE THREAD

**Issue by wufeiafei** [BANKEX/web3swift#197]
how to get mnemonic from privatekey?

**Comment by shamatar** [comment]
Are you talking about BIP32 keystore? There is no direct backward conversion from the private key to the mnemonic part. At the point of creating of a keystore you should ask a user to save a pass phrase. After seed phrase is converted to some initial entropy the “master key is derived” and the initial entropy is discarded, so the restoration of a seed phrase is not possible
