### ISSUE TITLE
Wrong conversation of the Wei.

### ISSUE THREAD

**Issue by OlegGordiichuk** [BANKEX/web3swift#2]
[Method](https://github.com/BANKEX/web3swift/blob/master/web3swift/Contract/Classes/Web3%2BEth.swift#L68) return wrong value.

This issue is connected with lib that is download from **Cocoapods**.

In my case:
 **resultString** = "0x1c31de57e49fc00".
**balance** = 2031649376000000000

Expected result is one of this.

<img width="442" alt="2018-01-18 23 01 47" src="https://user-images.githubusercontent.com/3758731/35121314-a7c7cd3e-fca3-11e7-8381-d98558009484.png">

**Comment by shamatar** [comment]
Hello Oleg.

I'll look into this issue. A reference for contract address/network/method/expected return value would be appreciated.

Sincerely, Alex

**Comment by OlegGordiichuk** [comment]
@shamatar I find the problem. Problem is in cocoa pods. When you will set pod 'web3swift'. You will not use latest version of the lib. And in the version that is download from cocoa pods you can find this issue.

**Comment by shamatar** [comment]
Hello Oleg.

Please run 
```
pod update
```

I've removed the code you listed for quite some time already. Version 0.2.8 should fix an issue for you. Please check your code with a new version and close if everything is resolved.

Sincerely, Alex
