### ISSUE TITLE
KeyStoreManger has only one constructor 

### ISSUE THREAD

**Issue by 6epreu** [BANKEX/web3swift#20]
Hello dev team. 
I really wondering why you decided to implement only one constructor for keystoremanager that provides ability ONLY ready wallets from file. 

F.e. I want to store my wallets (EthereumKeystoreV3) in whatever location I want(UserDefaults, KeyChain, FileManger) and I want to be able init KeyStoreManager with pure EthereumKeystoreV3

Cause now I need to make huge amount of useless steps. Im storing my wallets in keychain and I need
1) get wallets from keychain
2) serialize them to user's directory
3) construct KeystoreManager
4) Start using the web3

Please add simple constructor to init KeyStoreManager with AbstractKeystore/EthereumKeystoreV3

**Comment by shamatar** [comment]
I've included those in the last git commit, now you can construct manager from a set of either v3 or bip32 keystores. Initial design was to provide a convenient method for developer to store all the keystores in a folder and just read from there.

Please note that storing keystores themselves in keychain is not necessary, there is no unencrypted private data in those. You can even iCloud backup and sync those. Although password MUST be stored in a keychain if you save it on behalf of the user.

Sincerely, Alex
