### ISSUE TITLE
libsodium generate a conflict with my project

### ISSUE THREAD

**Issue by corocraft** [BANKEX/web3swift#203]
Hello, 

I am trying to use web3swift but libsodium generate a conflict and i got a lot of errors. 
For example: 

While building module 'Foundation' imported from ...

System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:9: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:

My podfile is:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['ENABLE_BITCODE'] = 'NO'
end
end
end

target “project” do
use_frameworks!

pod 'AFNetworking', '~> 2.5.4'
pod 'AFNetworkActivityLogger'
pod 'Google/Analytics', '~> 1.0.0'
pod 'Firebase'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig’
pod 'TesseractOCRiOS'
pod 'web3swift', '~> 0.9.0'
end

What could be happening?

Regards

**Comment by corocraft** [comment]
My podfile is:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

target “project” do
	use_frameworks!

	pod 'AFNetworking', '~> 2.5.4'
	pod 'AFNetworkActivityLogger'
	pod 'Google/Analytics', '~> 1.0.0'
	pod 'Firebase'
	pod 'Firebase/Storage'
	pod 'Firebase/Messaging'
	pod 'Firebase/RemoteConfig’
	pod 'TesseractOCRiOS'
	pod 'web3swift', '~> 0.9.0'
end

**Comment by shamatar** [comment]
Hello @corocraft 

Never had a problem like this myself. Will create a dummy project with your podfile and check.

Sincerely, Alex

**Comment by corocraft** [comment]
Hello @shamatar,

Thank you for your answer. Finally, I could solve the problem. This was because libsodium is in C and it generates a lot of errors with header's librarys. I solved this renamed each file extension from .c to .m.

I don't know because this happened.

Regards,

**Comment by v57** [comment]
libsodium removed from web3swift
