### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by SteadyAction** [BANKEX/web3swift#204]
please support Carthage..
I know it wont be easy because its dependencies do not support Cartharge :(
but any change?

**Comment by shamatar** [comment]
I'll have a look what is the simplest way to make it work. Worst case I'll have to provide a custom repository for libsodium.

**Comment by SteadyAction** [comment]
@shamatar thank you and love you

**Comment by v57** [comment]
Added support for carthage and swift package manager
github "BANKEX/web3swift" ~> 1.1

**Comment by tomaszmedryk** [comment]
I get an error `Missing required modules: 'BigInt', 'CryptoSwift', 'PromiseKit', 'PromiseKit', 'Result', 'Result', 'secp256k1'`
