### ISSUE TITLE
Bug in EthereumTransaction.swift

### ISSUE THREAD

**Issue by MrShafiee** [BANKEX/web3swift#205]
Hi @shamatar ,
As you know in some transaction _"to"_ field is null, such as when we deploy new contract there is not any _"to"_ field, and in this way when we get details of transaction, _"to"_ field return null but in EthereumTransaction struct _"to"_ is not optional. for instance look at this response for get eth_getTransactionByHash function:

```
{
	"jsonrpc": "2.0",
	"id": 14,
	"result": {
		"blockHash": "0xdf0bb32ab935aeeec519b.....88bddc4b6c7ca04de5b114",
		"blockNumber": "0xb0c55",
		"from": "0x138795fb9a0ade.....79a927ce74afa",
		"gas": "0x2b2ccb",
		"gasPrice": "0x4a817c800",
		"hash": "0xe1ea3da32d6eb053912......54bfb33d41567",
		"input": "0x608060405...0",
		"nonce": "0xa",
		"to": null, =======> THIS IS NULL
		"transactionIndex": "0x0",
		"value": "0x0",
		"v": "0x1b",
		"r": "0x7aa6949e8c...bd5f185d550283caaa3f080fda",
		"s": "0x4fcabdce984c70......0dac559e0ec"
	}
}
```
and it return this error: **_Invalid value from Ethereum node_**
How should we fix this issue? Could you fix it?

**Comment by shamatar** [comment]
Hello @MrShafiee 

Thanks for report, will fix soon.

Sincerely, Alex

**Comment by shamatar** [comment]
@MrShafiee 

Can you check against master branch after #206 ?

**Comment by MrShafiee** [comment]
@shamatar 
Yes, it fixed correctly, thanks 👍 
Sincerely, Amin.
