### ISSUE TITLE
Can we get the contract address of a deployed contract?

### ISSUE THREAD

**Issue by kobiwaldi** [BANKEX/web3swift#212]
Is there nay chance to get the contract address of a deployed contract ?

**Comment by shamatar** [comment]
If you save a transaction hash, you can later ask the Ethereum node for a transaction details, and one of the fields will be the “contract address”. It’s possible to know the contract address before sending, although I don’t think I’ve made this method public

________________________________

**Comment by kobiwaldi** [comment]
ty for your reply ! I got it
