### ISSUE TITLE
How to listen the contract event?

### ISSUE THREAD

**Issue by BlueFlicker** [BANKEX/web3swift#216]
Hello, I don't know where the event listener.

**Comment by skywinder** [comment]
Hello. Me and Alex (@shamatar) as main maintainers are moving our development to the new repo ➡️  https://github.com/matterinc/web3swift ⬅️ 
Feel free continue discussion in the new repository. 👍 
Cheers.

**Comment by BlueFlicker** [comment]
installed web3swift version is 1.1.5

**Comment by skywinder** [comment]
This issue was moved to matterinc/web3swift#18

**Comment by vladaccess** [comment]
https://github.com/matterinc/web3swift/issues/18#issuecomment-419029161
