### ISSUE TITLE
'BigUInt' is ambiguous for type lookup in this conte

### ISSUE THREAD

**Issue by zyqiong** [BANKEX/web3swift#218]
after pod update,this error is shown:'BigUInt' is ambiguous for type lookup in this conte

**Comment by alexbtlv** [comment]
Try updating cocoapods. It worked for me, hope it works for you.

`sudo gem install cocoapods --pre`

**Comment by v57** [comment]
podfile updated

**Comment by ashchan** [comment]
Beta version of CocoaPods doesn't work for me. Ended up using this:

`import struct BigInt.BigUInt`

instead of:

`import BigInt`

**Comment by v57** [comment]
You can use release version of cocoapods
