### ISSUE TITLE
Smart Contract - Estimate Gas

### ISSUE THREAD

**Issue by FrankyAguilar** [BANKEX/web3swift#219]
I'm building the ability to send ERC-721 tokens to ETH Addresses.

The issue is different Smart Contracts have specific gas estimates. I cannot figure out how to Estimate the Gas of a SmartContract... Mostly because you have to provide options... which have a default limit and price.
So its failing to estimate...

`

let contractEAddress = EthereumAddress(contractAddress)
 
        do {
            let keystore = try loadKeystore()
            let keystoreManager = KeystoreManager([keystore])
            web3Main.addKeystoreManager(keystoreManager)
        } catch {
            print(error.localizedDescription)
            return
        }
       
        var option = Web3Options.defaultOptions()
        option.from = EthereumAddress(address!)
        print(option)
        
        if let contract = web3Main.contract(erc721ABI, at: contractEAddress) {
            
            let params = [ EthereumAddress(address!), EthereumAddress(toAddress), tokenID] as [AnyObject]
            let contractMethod = contract.method("transferFrom", parameters: params, extraData: Data(), options: option)
            let estimate = contractMethod?.estimateGas(options: option)
            print(estimate)

`

returns:
gas required exceeds allowance or always failing transaction

the default options provide:
gasLimit: Optional(90000), gasPrice: Optional(5000000000)

Which is wayyyy to low for the specific Smart Contract

**Comment by skywinder** [comment]
Hello. Me and Alex (@shamatar) as main maintainers are moving our development to the new repo ➡️  https://github.com/matterinc/web3swift ⬅️ 
Feel free continue discussion in the new repository. 👍 
Cheers.

**Comment by v57** [comment]
```
let gasPrice = ERC721(contractAddress, from: address).gasPrice.transfer(from: address, to: toAddress, token: tokenID)
```
