### ISSUE TITLE
Signing transaction without connecting to web3 provider

### ISSUE THREAD

**Issue by PetroShylaiev** [BANKEX/web3swift#22]
Hi! Thanx for you amazing library! I would like to know if there are any ways to sign transaction locally on iOS device without connecting to internet? 

'cos now if I understand correctly, to be able to sign transaction there need to be an instance web3 initiated with web3Provider. 

I'd like to calculate transaction hash and send it via etherscan api

**Comment by shamatar** [comment]
Hello @PetroShylaiev

Yes, af far as I remember you can create an EthereumTransaction, and than use EIP155Signer or FallbackSigner to sign it with a private key. You can also check Web3Signer if you utilize any of the Keystores

Let me know if you can do it, may be structs were not marked as public.

Sincerely, Alex

**Comment by PetroShylaiev** [comment]
@shamatar thanx for your response!

I've fixed it in my code by adding "public" to some entities. 

That's the realization without pod updating

`let privateAddressData = Data(hex: keys.privateKey)
                //Unlock pod and paste public init() {}
                let signer = EIP155Signer()
                try signer.sign(transaction: &transaction, privateKey: privateAddressData)
                //Unlock pod and make createRawTransaction method public
                let rawTransaction = EthereumTransaction.createRawTransaction(transaction: transaction)
                //Unlock pod and make params var public
                guard let parameters = rawTransaction?.params, let txHash = parameters.params[0] as? String else {
                    throw VolansError(errorDescription: R.string.localizable.transactionFailed())
                }
                print(txHash)`

**Comment by shamatar** [comment]
Hello @PetroShylaiev 

I've exposed some extra methods to be public, like transaction.encode(), so you can make something like
```
var transaction = EthereumTransaction(...)
transaction.nonce = ...
transaction. UNSAFE_setChainID(...)
EIP155Signer.sign(transaction, privateKey: ...)
let encoded:Data? = transaction.encode()
let hash:Data? = transaction.hash
let txid:String? = transaction.txid
```

Sincerely, Alex

**Comment by jlstr** [comment]
Hey guys,

Which package do I have to import in order to use the EIP155Signer?

Thanks
