### ISSUE TITLE
Web3.Utils.formatToEthereumUnits 

### ISSUE THREAD

**Issue by xiaoluSF** [BANKEX/web3swift#224]
Hello !
I have a value 100 `wei`, format to Ethereum with `fallbackToScientific` is true.
result is '100e-16',but the correct is `1.0e-16`. 
Same, 1000`wei` or 10000 `wei` all have the wrong result.
This's the code,`fullRemainder` should format to `x.xx..`,but it is not processed here.
Another option is delete the `break`,make result is `100e-18`
![image](https://user-images.githubusercontent.com/23251844/45870422-6e316680-bdbd-11e8-89b5-246dfb329b2b.png)

**Comment by skywinder** [comment]
This issue was moved to matterinc/web3swift#48
