### ISSUE TITLE
AbiElement.decodeReturnData supports only dynamicTypes

### ISSUE THREAD

**Issue by 6epreu** [BANKEX/web3swift#23]
I have simple function in smart contract 

`{
    "constant": true,
    "inputs": [
      {
        "name": "log",
        "type": "address"
      }
    ],
    "name": "getEntriesAmount",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "payable": false,
    "type": "function"
  }`

Function returns value of type uint256 which after parsing in Contract object become staticABIType
When Im trying to execute this function I receiving nil result because of this 

![2018-03-09_17-06-37](https://user-images.githubusercontent.com/1928745/37211225-500b6fa2-23bc-11e8-8dd6-e1017095f79f.png)

**Comment by shamatar** [comment]
Hello @6epreu 

This is a special case when there is no data returned by the server ("0x" returned in hex, empty data). I've included special cases for bytes and string, although there is nothing in standard what behavior is defined for uint256, etc types. In principle I can put default empty values for every type, but some real live behavior testing is required. If you have some piece of code that can be deployed to test against - it would help a lot.

Sincerely, Alex

**Comment by 6epreu** [comment]
I will investigate other libraries for behavior. Think it’s good to send not nil. Empty dictionary or maybe appropriate empty enum.
