### ISSUE TITLE
how to get Mnemonic from BIP32Keystore?

### ISSUE THREAD

**Issue by SteadyAction** [BANKEX/web3swift#234]
how can I get Mnemonic from BIP32Keystore?
After I create a wallet using Bip32Keystore, I want to show user their mnemonic whenever they want.
How can I do that?

**Comment by v57** [comment]
BIP32Keystore contains seed generated by mnemonics

So you should generate Mnemonics first, then create BIP32Keystore

```
let mnemonics = try! BIP39.generateMnemonics(bitsOfEntropy: 256)!
let keystore = BIP32Keystore(mnemonics: mnemonics, password: "", mnemonicsPassword: "")!
```
Sorry for that try! and unwrap syntax i will change this in the next update

**Comment by SteadyAction** [comment]
@v57  yes I understand i can create new Mnemonics but... After I create keystore and save in on device, I want to get the mnenomic words again from the keystore I saved. How do I get mnemonics?

**Comment by v57** [comment]
You should store users mnemonics separatly. Bip32 is only contains PBKDF2SHA512 hash of this mnemonics so you cannot restore it

**Comment by SteadyAction** [comment]
@v57  is there any way to store it safely?

**Comment by v57** [comment]
For non jailbroken device you can just use NSUserDefaults. For jailbroken device its better to encrypt it using users pincode

**Comment by v57** [comment]
Also noone would store sensitive data on jailbroken device. You can add warning message if you detect that app is running on jailbroken device
