### ISSUE TITLE
Missing module Result

### ISSUE THREAD

**Issue by mjoselli** [BANKEX/web3swift#238]
Hello,

I am trying to use the Web3swift in Xcode 10.0 (Deployment target 12.0). But when the compiler tries to build the Pod, it says "No such Module 'Result'" in TransactionSigner.swift.
I have tried to manually install the pod Result, tried to change the Deployment target and also looked into the example from GitHub (where you have a different web3swift.xconfig). But if no luck. Could you help me?

**Comment by v57** [comment]
Sorry just fixed that. Please run `pod update`
