### ISSUE TITLE
Develop branch 404

### ISSUE THREAD

**Issue by Littlebigdondon** [BANKEX/web3swift#24]
I’d like to possibly contribute to the framework as I build out an app to monitor and interact with my nodes. Which branch should I be pulling from? Documentation says to pull from the develop branch, but the link leads to a 404 error and the develop branch does not exist (at least for the public).

**Comment by shamatar** [comment]
You can base your PR on the master branch, for now I've deleted dev branch as there is only one developer actively working on 0.4
