### ISSUE TITLE
The password for keystore file now is invalid？

### ISSUE THREAD

**Issue by phantomAssassion** [BANKEX/web3swift#242]
I am trying to import wallet by keystore file in another app,but the password is invalid?
Since this lib update to version-1.18？

**Comment by v57** [comment]
I will check it now. If you need live discussion, you can join our [Discord Channel](https://discord.gg/3ETv2ST)

**Comment by v57** [comment]
Okay i fixed and added a test so that would never happen again. We apologize for any inconvenience caused by this bug.
