### ISSUE TITLE
"crash" with EthereumTransaction.fromRaw()

### ISSUE THREAD

**Issue by rubikva** [BANKEX/web3swift#244]
I try to get EthereumTransaction from transaction raw data : 
`
let transactionString = "0xa9059cbb00000000000000000000000083b0b52a887a4c05429ee6d4619afeb8007c1a330000000000000000000000000000000000000000000000000001c6bf52634000"
let transactionData = Data.fromHex(transactionString)!
let rawTransaction = EthereumTransaction.fromRaw(transactionData) // Crash`

but at the last line, I've had something like a crash, but without errors, warnings, etc... An application just close and debugger detached from the process. After debugging I found that code stop working at `RLP.decode(_ raw: Data)`, at line `let (of, dl, t) = decodeLength(bytesToParse)`, it just stop working here and exit from app without any errors, also after this "crash" I can't run my app again, only after reopen simulator. Any idea about this?

**Comment by v57** [comment]
I will check this one today

**Comment by rubikva** [comment]
Thank you.

**Comment by v57** [comment]
I fixed that. Now it returns nil

**Comment by rubikva** [comment]
Thank's a lot!
