### ISSUE TITLE
connecting to local private network

### ISSUE THREAD

**Issue by darwinharianto** [BANKEX/web3swift#250]
have made a local Geth network, then I want to connect it to my iOS. How do I specify and call my own local network to be connected to my iPhone? I

**Comment by v57** [comment]
```
let url = URL(string: "http://127.0.0.1:8545")!
Web3.default = Web3(url: url)
```
Now all your request will connect to 127.0.0.1. And for iphone you need to change that to your wifi address. Also geth node should accept connections from non-localhost ip. To set that run your geth with parameter `--rpcaddr 0.0.0.0`

**Comment by darwinharianto** [comment]
PromiseKit: warning: `wait()` called on main thread!

**Comment by v57** [comment]
Use http. You cannot connect to https address without a certificate. For wait() warning just run this code in non-main thread. Because it sends request to find node network id

**Comment by darwinharianto** [comment]
I tried to use `    override func viewDidLoad() {
        super.viewDidLoad()
        options.from = "0xE6877A4d8806e9A9F12eB2e8561EA6c1db19978d"
        let address: Address = "0x74fd85d212d0878b5045801e4582714290aec990"
        let url = URL(string: "http://127.0.0.1:8545")!
        Web3.default = Web3(url: url)!
        let balance = try? Web3.default.eth.getBalance(address: address)
        print(balance ?? 0)
    }`

and the error says this `2018-11-09 10:26:57.852342+0900 Web3SwiftExample[1479:259647] [] nw_socket_handle_socket_event [C1:2] Socket SO_ERROR [61: Connection refused]
2018-11-09 10:26:57.852812+0900 Web3SwiftExample[1479:259647] TIC TCP Conn Failed [1:0x2802a8b40]: 1:61 Err(61)
2018-11-09 10:26:57.853437+0900 Web3SwiftExample[1479:259647] Task <051F0B21-C262-48A3-8FB2-115376E01307>.<1> HTTP load failed (error code: -1004 [1:61])
2018-11-09 10:26:57.853589+0900 Web3SwiftExample[1479:259646] Task <051F0B21-C262-48A3-8FB2-115376E01307>.<1> finished with error - code: -1004`

when I used `let url = URL(string: "http://14:20:5e:01:98:1e")!` `App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.`occurs, even if I have allow arbritary load

**Comment by v57** [comment]
for ipv6 address im using:
```
var options = Web3Options.default
options.from = "0xE6877A4d8806e9A9F12eB2e8561EA6c1db19978d"
let address: Address = "0x74fd85d212d0878b5045801e4582714290aec990"
let url = URL(string: "http://[2002:2ebc:e31::821:fa75:3b9:9e6d]:8545")!
Web3.default = Web3(url: url)!
let balance = try? Web3.default.eth.getBalance(address: address)
print(balance ?? 0)
```

and running geth with:
```
geth --rpc --rpccorsdomain '*' --rpcapi 'eth,web3,personal,net,miner,admin,debug,txpool' --nodiscover --dev --rpcport 8545 --rpcaddr [::]
```

**Comment by darwinharianto** [comment]
thanks a lot, this solved my problem

`sudo geth --datadir /ether/ACPrivateChain --networkid 34711 --rpcaddr 0.0.0.0 --rpc `

adding rpcaddr and rpc make it discoverable

and change the ip for the url `let url = URL(string: "http://172.21.208.121:8545")!`
