### ISSUE TITLE
Cannot load module 'Web3swift' as 'web3swift'

### ISSUE THREAD

**Issue by svenPepsi** [BANKEX/web3swift#251]
Hello. There was a problem with the module. I tried to solve this problem in various ways, but it does not work. Who had a similar problem, please tell me how to solve it.

P.S: I read the post on stackOverflow, and it said that there might be a problem in cocoa pods or Xcode or swift version. I use xCode 10.1, swift 4.2, cocoapods v.1.5.3, in Podfile i'am use pod 'web3swift', '~> 2.0'

<img width="273" alt="2018-11-05 18 38 03" src="https://user-images.githubusercontent.com/44780996/48012489-c8e30f80-e12a-11e8-8dec-615b0274880a.png">

**Comment by v57** [comment]
use `pod 'web3swift', :git => 'https://github.com/bankex/web3swift.git', '~> 2.0'`

**Comment by svenPepsi** [comment]
@v57 thx, but I can't pod install, I have error [!] Invalid `Podfile` file: syntax error, unexpected '\n', expecting =>.

**Comment by v57** [comment]
Oh sorry, its `pod 'web3swift', :git => 'https://github.com/bankex/web3swift.git'`
