### ISSUE TITLE
Crash with `BigUInt` after updating from 2.0.1 to 2.0.3

### ISSUE THREAD

**Issue by tzm41** [BANKEX/web3swift#252]
I saw that `Fixed BigUInt conflict` is in release note of 2.0.2. Was there anything changed that lead to `BigUInt` crashing? Specifically, in my project it is crashing when I try to get the `BigUInt` variable's description property.

**Comment by v57** [comment]
Let me check that. I just removed objective-c biguint class

**Comment by tzm41** [comment]
Thank you!

**Comment by tzm41** [comment]
Cleaning the project helped, thanks!
