### ISSUE TITLE
calling a function from contract

### ISSUE THREAD

**Issue by darwinharianto** [BANKEX/web3swift#253]
I have called a get() function from a deployed contract. but I cannot call a set() function on a deployed contract. it always gives out an error.
        `do{`
           `let contract = try Web3.default.contract(abi, at: contractAddress)`
          `  let result = try contract.method("set", parameters: [String("asdjasd")], options: options)`
           `let callResult = try result.call(options: nil)`
         `  print(try callResult.string())`
        `}catch{`
         `  print("error")`
      `  }`

the contract takes string as the input parameter. Which part is wrong from the snippet above? I don't understand. Thanks for replying

**Comment by v57** [comment]
Can you show me how your function in solidity looks like?

**Comment by v57** [comment]
If its 
```
set(string input) public view returns(string)
```
Then you can just call
```
let string = try contractAddress.call("set(string)", "hello").wait().string()
```

**Comment by darwinharianto** [comment]
the sol function is like this 

```
 pragma solidity ^0.4.13;
    
 contract MessageContract {
    string message = "Hello World";
    
    function set(string newMessage) public returns(bool success){
        message = newMessage;
        return true;
    }

    function get() public constant returns(string) {
        return message;
    }
 }
```

**Comment by v57** [comment]
This is a setter function. You need to run `send` instead of `call`
```
let transaction = try contractAddress.send("set(string)", "hello").wait()
```

**Comment by darwinharianto** [comment]
it still catches error

this is how I call it



```
        do{
            let transaction = try contractAddress.send("set(string)", "hello").wait()
            print(transaction)
        }catch{
            print("error")
        }
```

**Comment by v57** [comment]
Can you print your error?

**Comment by darwinharianto** [comment]
it doesn't display anything. it just call my catch function. how to get the error message?

**Comment by v57** [comment]
When inside catch function you can use catched error
```
        do {
            let contract = try Web3.default.contract(abi, at: contractAddress)
            let result = try contract.method("get", options: options)
            let callResult = try result.call(options: nil)
            print(try callResult.string())
        } catch {
            print("error:", error)
        }
```

**Comment by darwinharianto** [comment]
the error is this `error: inputError("No \'from\' field provided")`

**Comment by v57** [comment]
Ah sorry you need to set sender address
```
var options = Web3Options.default
options.from = yourSenderAddress
let transaction = try contractAddress.send("set(string)", "hello", options: options).wait()
```
Make sure that you have yourSenderAddress in the keystore and you have enough balance to send the transaction

**Comment by v57** [comment]
We can also continue discussion in our [discord channel](https://discord.gg/3ETv2ST)

**Comment by darwinharianto** [comment]
Thanks for your reply. It works perfectly, but I need to manually sign in from the console. How can I set the password from the code?

**Comment by v57** [comment]
If you using private node like ganache then you can just copy mnemonics
<img width="1312" alt="screenshot 2018-11-14 at 13 03 35" src="https://user-images.githubusercontent.com/2669441/48475538-1be55280-e80e-11e8-982b-4b8cfe2aedc2.png">

Now you can use this account in web3swift:
```
let mnemonics = try Mnemonics("nation tornado double since increase orchard tonight left drip talk sand mad")
Web3.default = .local(port: 9545)
let web3 = Web3.default
web3.keystoreManager = try KeystoreManager([BIP32Keystore(mnemonics: mnemonics)])
let account = web3.keystoreManager!.addresses[0]

var options = Web3Options.default
options.from = account
let transaction = try contractAddress.send("set(string)", "hello", options: options).wait()
```

**Comment by darwinharianto** [comment]
I created the account using the javascript console. personal.newAccount() and then putting in the password afterwards. I don't have mnemonics.

**Comment by v57** [comment]
Sorry for the late answer. Its better to use [Ganache](https://truffleframework.com/ganache) for local testing cause it works with mnemonics (which you will use in the real world). 

Geth doesn't support mnemonics. You need to generate your account using web3swift, save its mnemonics or private key and write its address in geth json to set the initial eth balance.

But you still can send ether from geth generated account to yours. So to do that:
* generate mnemonics and get your address in web3swift
```
let mnemonics = try Mnemonics()
print(mnemonics.string, BIP32Keystore(mnemonics: mnemonics).addresses[0])
```
in our case this would be 
mnemonics: "nation tornado double since increase orchard tonight left drip talk sand mad"
address: "0xDf2bC70175311A6807F085e54881Fc4931359dBF"

now run in geth:
```
eth.sendTransaction({from:eth.coinbase, to: "0xDf2bC70175311A6807F085e54881Fc4931359dBF", value: web3.toWei(100, "ether")})
```
this should send 100 ether to your account

**Comment by darwinharianto** [comment]
Thank you for the reply. I haven't set up an environment using ganache. I will try to set up one later. Can consider this as fixed
