### ISSUE TITLE
How to send Ether?

### ISSUE THREAD

**Issue by pandeyshivang** [BANKEX/web3swift#26]
Nonce: 0
Gas price: 10000000000
Gas limit: 21000
To: 0x9b74194598b3958F4d297a88D2Cf08D6AC9e94F2
Value: 1
Data: 0x
v: 43
r: 80287024288568798399909076275234636204102624376660596706812468658517829864183
s: 53520257226279840727769044968540293274665086271749812008238144501231151363572
Intrinsic chainID: Optional(4)
Infered chainID: Optional(4)
sender: Optional("0x9b74194598b3958F4d297a88D2Cf08D6AC9e94F2")
hash: Optional("0x31d226fe625a0a7f7cd88f0bac8bb1b322f99e2921243216e4cdefec04f50108")

but return nil

**Comment by shamatar** [comment]
Hello @pandeyshivang 

Use the following function as reference. You should not get an error there if you have enough funds on you account (the code below makes a temporary keystore without funds)

```
    func testEthSendExample() {
        let web3 = Web3.InfuraMainnetWeb3()
        let sendToAddress = EthereumAddress("0x6394b37Cf80A7358b38068f0CA4760ad49983a1B")
        let tempKeystore = try! EthereumKeystoreV3(password: "")
        let keystoreManager = KeystoreManager([tempKeystore!])
        web3.addKeystoreManager(keystoreManager)
        let contract = web3.contract(Web3.Utils.coldWalletABI, at: sendToAddress, abiVersion: 2)
        var options = Web3Options.defaultOptions()
        options.value = Web3.Utils.parseToBigUInt("1.0", units: .eth)
        options.from = keystoreManager.addresses?.first
        let intermediate = contract?.method("fallback", options: options)
        guard let result = intermediate?.send(password: "") else {return XCTFail()}
        switch result {
        case .success(_):
            return XCTFail()
        case .failure(let error):
            guard case .unknownError = error else {return XCTFail()}
        }
    }
```

**Comment by pandeyshivang** [comment]
i want to send ether not token.

**Comment by jlstr** [comment]
Hello @shamatar,

I would like to know exactly how you do this in the latest version. Do you think it's possible to have an example? I'm not sure If much has changed, but I'd really appreciate it If I could see it.

Thank you very much my friend.
-Jose
