### ISSUE TITLE
Swift Compiler Error: 'UIKit/UIKit.h' file not found

### ISSUE THREAD

**Issue by liweiz** [BANKEX/web3swift#260]
I downloaded the source code and tried to run tests. It seems the process stopped at build stage and got the warning for web3swift.h file under Sources/ObjectiveC:

Swift Compiler Error: 'UIKit/UIKit.h' file not found

How to solve this?

Thanks,

Liwei

**Comment by v57** [comment]
I will fix that in 5 mins. Also project tests and carthage only works in iOS because of secp256k1.swift dependency

**Comment by v57** [comment]
I will make my own version of secp256k1 tomorrow

**Comment by liweiz** [comment]
@v57 Thank you for such quick responses.

**Comment by v57** [comment]
Ok i released 2.0.4 version

**Comment by liweiz** [comment]
I have these new errors. I do not have an active Apple Developer Program membership currently. Does it matter to have that? I have not worked on XCode for 2 years. IIRC, Apple does not charge for some development membership any more. Please correct me, if my understanding is incorrect.

![screen shot 2018-11-13 at 3 25 17 pm](https://user-images.githubusercontent.com/2466618/48440975-57254a00-e758-11e8-8225-1af60587c5b7.png)

**Comment by v57** [comment]
Just set project and tests team to none

**Comment by v57** [comment]
Also don't forget to run `carthage update` to download and compile dependencies

**Comment by liweiz** [comment]
Sorry to get back to you late. I was keeping trying to solve the signing issue, which I believe caused by my limited familiarity with Xcode. But I did not make any progress.

Thank you for suggesting installing dependencies via carthage. That part just works. It mostly looks like it's working like 2 years ago.

The error message I'm getting is as below:

![screen shot 2018-11-13 at 8 30 53 pm](https://user-images.githubusercontent.com/2466618/48454113-0cb9c280-e784-11e8-9ec3-0a28b9fdf7b1.png)

My current settings for signing is:

![screen shot 2018-11-13 at 8 31 56 pm](https://user-images.githubusercontent.com/2466618/48454132-21965600-e784-11e8-943a-61893a032f25.png)

I'm not able to find the place to set signing for target "Tests".

Any tip for the things I'm doing is incorrect?

Thanks,

Liwei

**Comment by v57** [comment]
I just removed the team and selected iphone xs simulator and it works
<img width="1003" alt="screenshot 2018-11-14 at 12 54 55" src="https://user-images.githubusercontent.com/2669441/48474959-c65c7600-e80c-11e8-8fb8-58a80852594e.png">
<img width="1012" alt="screenshot 2018-11-14 at 12 55 55" src="https://user-images.githubusercontent.com/2669441/48474967-c8bed000-e80c-11e8-8bb6-8deb939c67f6.png">
<img width="389" alt="screenshot 2018-11-14 at 12 56 04" src="https://user-images.githubusercontent.com/2669441/48474974-cb212a00-e80c-11e8-903a-819d2a286c5a.png">

**Comment by liweiz** [comment]
Thank you for your help.
