### ISSUE TITLE
Json restore wallet

### ISSUE THREAD

**Issue by MaxPaymon** [BANKEX/web3swift#263]
Hello! Why, when  creating a wallet using a Json data, the function does not check the password from the file?

**Comment by v57** [comment]
Password for a private key?

**Comment by MaxPaymon** [comment]
No. I used this function 

<img width="1013" alt="2018-11-23 21 56 44" src="https://user-images.githubusercontent.com/29461219/48954314-c249fa00-ef6a-11e8-8f27-0c1bc4b3ea05.png">

**Comment by v57** [comment]
Keystore doesn't decrypt private key. You need to set the password every time you use it (like for signing messages or sending transactions). If you need to check for that, you can just call
```
try keystore.UNSAFE_getPrivateKeyData(password: yourPassword, account: keystore.addresses[0])
```
After your init

**Comment by MaxPaymon** [comment]
Thank you very much! It's work for me.
