### ISSUE TITLE
Carthage build failed

### ISSUE THREAD

**Issue by liweiz** [BANKEX/web3swift#266]
![screen shot 2018-12-03 at 7 58 08 pm](https://user-images.githubusercontent.com/2466618/49411182-f1642680-f735-11e8-8d08-095cf804b6fd.png)

cartfile

```bash
github "BANKEX/web3swift" ~> 2.1
```

Any idea on where to look at? The log file is too big. I can post it here if needed. The last few lines:

```bash
** ARCHIVE FAILED **
The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

Thanks,

Liwei

**Comment by v57** [comment]
Carthage only works on iOS for now (because of secp256k1.swift library). I will fix that today

**Comment by v57** [comment]
Should work now in 2.1.3
