### ISSUE TITLE
there is some error in example

### ISSUE THREAD

**Issue by lianchengjiang** [BANKEX/web3swift#27]
![image](https://user-images.githubusercontent.com/8663212/37865837-0dad89a8-2fbd-11e8-8f2a-d3abde00c1c5.png)

**Comment by pandeyshivang** [comment]
Dont follow example...

**Comment by skywinder** [comment]
@lianchengjiang thanks, can you specify, which version of library and XCode are you using?

**Comment by shamatar** [comment]
Use tests as an example, the code of Example itself is not updated
