### ISSUE TITLE
Create a W3EthereumTransaction in Objective-C

### ISSUE THREAD

**Issue by ozamihir1990** [BANKEX/web3swift#271]
Hello,
I have already asked this question in ethereum stackexchange. Here is the link : [https://ethereum.stackexchange.com/questions/65150/create-a-signed-transactionerc20-does-not-work-in-objective-c](url)
**My Transaction description:**

> Transaction
Nonce: 1
Gas price: 3000000000
Gas limit: 200000000000000
To: 0xcC8fcA01C2ffD24F6977F57526a6248E8F77Ad86
Value: 1
Data: a9059cbb000000000000000000000000cc8fca01c2ffd24f6977f57526a6248e8f77ad860000000000000000000000000000000000000000000000000000000000000001
v: 1
r: 0
s: 0
Intrinsic chainID: Optional(ropsten)
Infered chainID: Optional(mainnet)
sender: nil
hash: Optional(32 bytes)

I have changed some of the code but still I have some doubts/issues.
1) How to get Nonce dynamically? Right now I have passed static 1.
2) How to get Gas price and Gas limit Dynamically? Right now I have passed static Gas price and Gas limit.
3) How to pass Value dynamically? Right now I have passed static value.
4) What is Intrinsic chainID and Infered chainID?
5) How to change my chainID from mainnet to ropsten? 
Right now I have done `[transaction UNSAFE_setChainID:W3NetworkId.ropsten];`
6) How to pass sender in W3EthereumTransaction?
7) What is hash in `W3EthereumTransaction`?

**Comment by v57** [comment]
1,2,3: Nonce, gas price, gas limit and value sets automatically if you make them nil.
4: Estimated chain id
5: Just set the default Web3 provider:
```
W3Web3 *web3 = [[W3Web3 alloc] initWithInfura: [W3NetworkId ropsten]];
[W3Web3 setDefault:web3];
```
And then create transaction

6. To pass sender just set him in W3Options.from
7. Transaction hash is a transaction id. You can check current transaction status from this hash. You can also check transaction on [etherscan](https://etherscan.io)
