### ISSUE TITLE
How can I create an Web3 instance in a OC project

### ISSUE THREAD

**Issue by Yuan91** [BANKEX/web3swift#272]
In OC project ,I can only create W3Web3 instance,but I want to use Web3 instance to send erc20

**Comment by v57** [comment]
All classes with W3 prefix are just objective-c aliases for its swift classes. So W3Web3 contains Web3 object inside it and replicates its functions.

To change node address and network id just use:
```
W3Web3 *node = [[W3Web3 alloc] initWithInfura: [W3NetworkId ropsten]];
[W3Web3 setDefault: node];
```

**Comment by Yuan91** [comment]
> All classes with W3 prefix are just objective-c aliases for its swift classes. So W3Web3 contains Web3 object inside it and replicates its functions.
> 
> To change node address and network id just use:
> 
> ```
> W3Web3 *node = [[W3Web3 alloc] initWithInfura: [W3NetworkId ropsten]];
> [W3Web3 setDefault: node];
> ```
Thank you for your prompt reply.
I searched some documents，it recommend me  to do this:
`let web3Rinkeby = Web3.InfuraRinkebyWeb3()
  web3Rinkeby.addKeystoreManager(keystoreManager)
   let coldWalletABI = "[{\"payable\":true,\"type\":\"fallback\"}]"
   options = Web3Options.defaultOptions()
   options.gas = BigUInt(21000)
   options.value = BigUInt(1000000000000000)
    options.from = sendee
     let intermediateSend = web3Rinkeby.contract(coldWalletABI, at: coldWalletAddress)?.method(options: options)
    res = intermediateSend?.send(password: "BANKEXFOUNDATION")`

but I can not call contract using W3Web3 instance

**Comment by v57** [comment]
There is W3ERC20 class for ERC20 tokens. It uses default provider for its requests.

**Comment by Yuan91** [comment]
Thanks again!
In swift , I can use like this:
`let web3Rinkeby = Web3.InfuraRinkebyWeb3()`
`let intermediateSend = web3Rinkeby.contract(coldWalletABI, at: coldWalletAddress)?.method(options: options)`

Is there a way let me to call `contract` use W3Web3 instance

**Comment by v57** [comment]
@Yuan91 > If I want to send a certain amount token ,how can I set `options.value`
> 
> Can you show me an example code . Thanks

options.value is amount of ether you want to send.
If you want to send ether:
```
NSString *yourPassword = @"••••••••••••••••••••••••••••";
W3Address *yourAddress = [web3 addAccountWithMnemonics:@"nation tornado double since increase orchard tonight left drip talk sand mad" password:yourPassword error:&error];

W3Address *recipient = @"0x1111222233334444555566667777888899990000".address;
W3UInt *amount = [[W3UInt alloc] init:@"0.0001" units:W3UnitsEth];

W3Options *options = [W3Options default];
options.from = yourAddress;

W3TransactionSendingResult *result = [[web3.eth sendETHTo:recipient amount:amount extraData:[NSData new] options:options error:&error] sendWithPassword:yourPassword options:nil onBlock:@"latest" error:&error];
```

For ERC20 tokens:
```
W3Address *tokenAddress = @"0x0000111122223333444433332222111100001111".address;
W3ERC20 *token = [[W3ERC20 alloc] initWithAddress:tokenAddress from:yourAddress password:yourPassword];

W3Address *recipient = @"0x1111222233334444555566667777888899990000".address;
W3NaturalUnits *amount = [[W3NaturalUnits alloc] initWithString:@"0.0001" error:nil];
W3TransactionSendingResult *result = [token transferTo:recipient naturalUnits:amount error:&error];
```

**Comment by Yuan91** [comment]
Thanks again for your help.
When I use your example code, I can transfer ether successfully. But I can not transfer tokens,here is my code:

`W3Web3 *web3 = [[W3Web3 alloc]initWithInfura:W3NetworkId.mainnet];`
`NSError *error = nil;`
`NSString *yourPassword = @"mypassword";`
 ` NSData *privateKey = [@"myPrivateKeyString" toHexData];`
` W3Address *yourAddress = [web3 addAccountWithPrivateKey:privateKey password:yourPassword error:&error];`
   ` W3Address *tokenAddress = @"0xabC1280A0187a2020cC675437aed400185F86Db6".address;`

` W3ERC20 *token = [[W3ERC20 alloc] initWithAddress:tokenAddress from:yourAddress password:yourPassword];`
   `W3Address *recipient = @"0x32db422042f85f8e0c0d95aca6c8a6e41dcb3491".address;`
   `W3NaturalUnits *amount = [[W3NaturalUnits alloc] initWithString:@"1.5" error:&error];`
    ` W3TransactionSendingResult *result = [token transferTo:recipient naturalUnits:amount error:&error];`
    
It throws an error:
`Expected to decode Array<Any> but found a dictionary instead.`

I am so sorry to trouble you again!

**Comment by Yuan91** [comment]
> Thanks again for your help.
> When I use your example code, I can transfer ether successfully. But I can not transfer tokens,here is my code:
> 
> `W3Web3 *web3 = [[W3Web3 alloc]initWithInfura:W3NetworkId.mainnet];`
> `NSError *error = nil;`
> `NSString *yourPassword = @"mypassword";`
> ` NSData *privateKey = [@"myPrivateKeyString" toHexData];`
> ` W3Address *yourAddress = [web3 addAccountWithPrivateKey:privateKey password:yourPassword error:&error];`
> ` W3Address *tokenAddress = @"0xabC1280A0187a2020cC675437aed400185F86Db6".address;`
> 
> ` W3ERC20 *token = [[W3ERC20 alloc] initWithAddress:tokenAddress from:yourAddress password:yourPassword];`
> `W3Address *recipient = @"0x32db422042f85f8e0c0d95aca6c8a6e41dcb3491".address;`
> `W3NaturalUnits *amount = [[W3NaturalUnits alloc] initWithString:@"1.5" error:&error];`
> ` W3TransactionSendingResult *result = [token transferTo:recipient naturalUnits:amount error:&error];`
> 
> It throws an error:
> `Expected to decode Array<Any> but found a dictionary instead.`
> 
> I am so sorry to trouble you again!

**Comment by v57** [comment]
Maybe you don't have enough balance. Also you should send transactions from non-main queue

**Comment by v57** [comment]
You can try this code if you want to see that it works:
```
NSError *error;
W3Web3 *web3 = [[W3Web3 alloc] initWithInfura:[W3NetworkId ropsten]];
[W3Web3 setDefault: web3];

W3Address *account = [web3 addAccountWithMnemonics:@"reason liar code oxygen either tower skate into cancel matter used super" password:@"" error:&error];

W3UInt *amount = [[W3UInt alloc] init:@"0.001" decimals:18];
W3Options *options = [W3Options default];
options.from = account;

W3TransactionSendingResult *result = [@"0x362fa7D41A47874CF5231DC12AC7CA1339D1090D".address sendWithMethod:@"transfer(address,uint256)" arguments:@[@"0x69Eb8Ec67aD177D0f59dc52E1c0E6aac4d87324D", amount] password:@"" options:options error:&error];

NSLog(@"%@", result.transactionHash);
```

Same using native W3ERC20 class:
```
NSError *error;
W3Web3 *web3 = [[W3Web3 alloc] initWithInfura:[W3NetworkId ropsten]];
[W3Web3 setDefault: web3];

W3Address *account = [web3 addAccountWithMnemonics:@"reason liar code oxygen either tower skate into cancel matter used super" password:@"" error:&error];

W3ERC20 *token = [[W3ERC20 alloc] initWithAddress:@"0x362fa7D41A47874CF5231DC12AC7CA1339D1090D".address from:account password:@""];

W3NaturalUnits *amount = [[W3NaturalUnits alloc] initWithString:@"0.001" error:&error];
W3TransactionSendingResult *result = [token transferTo:@"0x69Eb8Ec67aD177D0f59dc52E1c0E6aac4d87324D".address naturalUnits:amount error:&error];

NSLog(@"%@", result.transactionHash);
```

This will send 0.001 DOLL tokens in ropsten network and prints transaction hash that you can use here:
https://ropsten.etherscan.io/

**Comment by MaxPaymon** [comment]
Hello! I tried to send an EPC20 token: 
<img width="965" alt="2019-01-16 17 37 11" src="https://user-images.githubusercontent.com/29461219/51249655-bcdebe00-19b5-11e9-93de-6e52e2af385e.png">

If I pass a value "1" , then the transaction is sent with the necessary parameters, but it is sent as a normal ETH transaction. At the time of transfer, he writes that 0.000000001 ERC20 tokens are being sent. In the end result, I get this:

<img width="1173" alt="2019-01-16 17 38 28" src="https://user-images.githubusercontent.com/29461219/51249808-47272200-19b6-11e9-97ed-b36369b5c197.png">
<img width="1181" alt="2019-01-16 17 38 37" src="https://user-images.githubusercontent.com/29461219/51249809-47272200-19b6-11e9-8977-b06392e5d10d.png">

If I pass a value "1000000000" , then i get error: "Failed to fetch gas estimate"

**Comment by v57** [comment]
<img width="249" alt="screenshot 2019-01-16 at 17 36 30" src="https://user-images.githubusercontent.com/2669441/51255933-493cb100-19b5-11e9-84f8-a41426e6ca87.png">
`token.options.to = Address(toAddress)`
There is your problem. .to address should be a contract address. And it's automatically fills for you. So you should remove this line. Also pls never test something on mainnet. Use ropsten or rinkeby instead :)

to set the network use: 
```
Web3.default = .infura(.rinkeby)
```

**Comment by CarolineOrlando** [comment]
> <img alt="screenshot 2019-01-16 at 17 36 30" width="249" src="https://user-images.githubusercontent.com/2669441/51255933-493cb100-19b5-11e9-84f8-a41426e6ca87.png">
> 
> ```
> token.options.to = Address(toAddress)
> ```
> There is your problem. .to address should be a contract address. And it's automatically fills for you. So you should remove this line. Also pls never test something on mainnet. Use ropsten or rinkeby instead :)
> 
> to set the network use:
> 
> ```
> Web3.default = .infura(.rinkeby)
> ```

Здравствуйте! Если я не указываю token.options.to, то транзакция отправляется как и в первом моем случае, только уходит она на Адрес контракта

<img width="1188" alt="2019-01-17 10 47 57" src="https://user-images.githubusercontent.com/46599755/51298186-602ae400-1a45-11e9-8bc6-bdff4b9951e6.png">

Я использую главную сеть, потому что, тестовую (.ropsten) я уже тестировал, эфири отправляются на ней корректно

**Comment by MaxPaymon** [comment]
> <img alt="screenshot 2019-01-16 at 17 36 30" width="249" src="https://user-images.githubusercontent.com/2669441/51255933-493cb100-19b5-11e9-84f8-a41426e6ca87.png">
> 
> ```
> token.options.to = Address(toAddress)
> ```
> There is your problem. .to address should be a contract address. And it's automatically fills for you. So you should remove this line. Also pls never test something on mainnet. Use ropsten or rinkeby instead :)
> 
> to set the network use:
> 
> ```
> Web3.default = .infura(.rinkeby)
> ```

Здравствуйте! Если я не указываю token.options.to, то транзакция отправляется как и в первом моем случае (Пытается, отправить обычный ETH с значением 0), только уходит она на Адрес контракта

<img width="1188" alt="2019-01-17 10 47 57" src="https://user-images.githubusercontent.com/29461219/51298268-c3b51180-1a45-11e9-9518-58f6d11dd301.png">

Я использую главную сеть, потому что, тестовую (.ropsten) я уже тестировал, эфири отправляются на ней корректно
Если есть возможность связаться другим способом, например Telegram, дайте пожалуйста знать. Очень нужна ваша помощь

**Comment by Yuan91** [comment]
> You can try this code if you want to see that it works:
> 
> ```
> NSError *error;
> W3Web3 *web3 = [[W3Web3 alloc] initWithInfura:[W3NetworkId ropsten]];
> [W3Web3 setDefault: web3];
> 
> W3Address *account = [web3 addAccountWithMnemonics:@"reason liar code oxygen either tower skate into cancel matter used super" password:@"" error:&error];
> 
> W3UInt *amount = [[W3UInt alloc] init:@"0.001" decimals:18];
> W3Options *options = [W3Options default];
> options.from = account;
> 
> W3TransactionSendingResult *result = [@"0x362fa7D41A47874CF5231DC12AC7CA1339D1090D".address sendWithMethod:@"transfer(address,uint256)" arguments:@[@"0x69Eb8Ec67aD177D0f59dc52E1c0E6aac4d87324D", amount] password:@"" options:options error:&error];
> 
> NSLog(@"%@", result.transactionHash);
> ```
> Same using native W3ERC20 class:
> 
> ```
> NSError *error;
> W3Web3 *web3 = [[W3Web3 alloc] initWithInfura:[W3NetworkId ropsten]];
> [W3Web3 setDefault: web3];
> 
> W3Address *account = [web3 addAccountWithMnemonics:@"reason liar code oxygen either tower skate into cancel matter used super" password:@"" error:&error];
> 
> W3ERC20 *token = [[W3ERC20 alloc] initWithAddress:@"0x362fa7D41A47874CF5231DC12AC7CA1339D1090D".address from:account password:@""];
> 
> W3NaturalUnits *amount = [[W3NaturalUnits alloc] initWithString:@"0.001" error:&error];
> W3TransactionSendingResult *result = [token transferTo:@"0x69Eb8Ec67aD177D0f59dc52E1c0E6aac4d87324D".address naturalUnits:amount error:&error];
> 
> NSLog(@"%@", result.transactionHash);
> ```
> This will send 0.001 DOLL tokens in ropsten network and prints transaction hash that you can use here:
> https://ropsten.etherscan.io/

Thanks for your continuous help. My problem has been solved

**Comment by v57** [comment]
Glad to help you 😉
