### ISSUE TITLE
BIP32Keystore and EthereumKeystoreV3 can't  getPrivateKeyData

### ISSUE THREAD

**Issue by jh235** [BANKEX/web3swift#28]
I found some problems in use, BIP32Keystore and EthereumKeystoreV3 can't  use  the function UNSAFE_getPrivateKeyData(password:, account:). 
KeystoreManager some property e.g addresses  not support   BIP32Keystore

**Comment by devSC** [comment]
+1

**Comment by devSC** [comment]
i can't get private key data when use`BIP32Keystore` by `UNSAFE_getPrivateKeyData(password:, account:)`. method.

And i got:  `Failed to sign transaction` error.

How to solve?

**Comment by jopinfly** [comment]
i found this error too.
it seems like `cipherText` will never equal to 32 in `BIP32Keystore` 's `getPrefixNodeData` method

**Comment by devSC** [comment]
@jh235 @jopinfly  I open a PR to fix this problem.

**Comment by jopinfly** [comment]
@devSC cool, it worked for me, thx

**Comment by jh235** [comment]
@devSC  Great, can you fix the bug with EthereumKeystoreV3? It also has some problem, thx!

**Comment by devSC** [comment]
@jh235 what problem have you meet?

**Comment by shamatar** [comment]
Hello everyone.

Would you check a 0.3.6 version regarding BIP32 keystore problem.

Sincerely, Alex

**Comment by jh235** [comment]
@devSC  EthereumKeystoreV3 can't use the function UNSAFE_getPrivateKeyData(password:, account:) too. And I want creating new wallets from a private key, It is impossible to achieve now. What are your best solutions?

**Comment by shamatar** [comment]
@jh235

The latest version has a test for KeystoreV3 creation and key export and it works, would you either try to follow the same way or describe your problem in more detail, may be with some code example

**Comment by jh235** [comment]
@shamatar Yes, The latest version has a test for KeystoreV3 creation and key export and it works,but I want to create a KeystoreV3 with privatekey, It is impossible to achieve now. thx!

**Comment by shamatar** [comment]
@jh235

There is a public constructor
‘’’
public init? (privateKey: Data, password: String = "BANKEXFOUNDATION") throws
‘’’

If you want to init it with a hex string (from user input), than convert it to Data first and pass to the constructor

**Comment by jh235** [comment]
@shamatar Thank you very much, my problem has been solved perfectly.Sorry, I didn't see the class of EthereumKeystoreV3. I'm only looking for BIP32Keystore.

**Comment by quzg** [comment]
@jh235  I want to create a BIP32Keystore from a private key, but if found that it is impossible to achieve. Do you know it? thx

**Comment by skywinder** [comment]
@quzg 
We have moved our development to the new repo.
➡️https://github.com/matterinc/web3swift ⬅️ 
Feel free continue discussion in the new repository. 👍
