### ISSUE TITLE
tuple data returns by smartcontract is missing

### ISSUE THREAD

**Issue by chymse67** [BANKEX/web3swift#280]
- Smart contract returns:

`0: tuple(uint16,string,string,string,uint16,uint32,bool,address)[]: 

1,Holiday,http://35.220.237.14/wp-content/uploads/2019/01/holiday@2x.png,Ngay nghi phep,10,0,true,0xE0879f2C7301A1D501c555B2B986a1EB48415eF0,

2,Cinema Ticket,http://35.220.237.14/wp-content/uploads/2019/01/cinema@2x.png,Ve xem phim,3,0,true,0xE0879f2C7301A1D501c555B2B986a1EB48415eF0,

4,Massage Ticket,http://35.220.237.14/wp-content/uploads/2019/01/book@2x.png,Ve Massage,1,0,true,0xE0879f2C7301A1D501c555B2B986a1EB48415eF0,

3,Book,http://35.220.237.14/wp-content/uploads/2019/01/book@2x.png,Sach,3,0,true,0xE0879f2C7301A1D501c555B2B986a1EB48415eF0,

5,Highland Coffee,http://35.220.237.14/wp-content/uploads/2019/01/highland@2x.png,Mot tach Highland Coffee,2,0,true,0xE0879f2C7301A1D501c555B2B986a1EB48415eF0`

- Web3Swift returns only  top 3 items. This is description of Web3Response

Printing description of ((Swift._ContiguousArrayStorage<AnyObject>)0x000060000077d1c0):
▿ 3 elements
  ▿ 0 : 8 elements
    - 0 : 1
    - 1 : Holiday
    - 2 : http://35.220.237.14/wp-content/uploads/2019/01/holiday@2x.png
    - 3 : Ngay nghi phep
    - 4 : 10
    - 5 : 0
    - 6 : 1
    - 7 : 0xE0879f2C7301A1D501c555B2B986a1EB48415eF0
  ▿ 1 : 8 elements
    - 0 : 2
    - 1 : Cinema Ticket
    - 2 : http://35.220.237.14/wp-content/uploads/2019/01/cinema@2x.png
    - 3 : Ve xem phim
    - 4 : 3
    - 5 : 0
    - 6 : 1
    - 7 : 0xE0879f2C7301A1D501c555B2B986a1EB48415eF0
  ▿ 2 : 8 elements
    - 0 : 3
    - 1 : Book
    - 2 : http://35.220.237.14/wp-content/uploads/2019/01/book@2x.png
    - 3 : Sach
    - 4 : 3
    - 5 : 0
    - 6 : 1
    - 7 : 0xE0879f2C7301A1D501c555B2B986a1EB48415eF0
Please tell me why, thanks you

**Comment by v57** [comment]
Can you show me how you parse it in your swift project?

**Comment by chymse67** [comment]
I found an issue at : ABIv2Decoding.swift - line 151
` let (v, c) = decodeSignleType(type: subType, data: dataSlice, pointer: subpointer)
                        guard let valueUnwrapped = v, let consumedUnwrapped = c else { break }`
v and c is nil while iterating (missing item 4 and 5)

**Comment by chymse67** [comment]
And connect timeout frequently occur

**Comment by v57** [comment]
Can you show me response in hex using
```
let address = Address(apvShopContractAddress)
let response = try! address.call("getListItems()", web3: Web3.default).wait()
print(response.data.hex)
```

**Comment by chymse67** [comment]
> Can you show me response in hex using:
> 
> ```
> let address = Address(apvShopContractAddress)
> let response = try! address.call("getListItems()", web3: strongSelf.web3).wait()
> print(response.data.hex)
> ```

Im using  let contract = try strongSelf.web3.contract(abi, at: Address(apvShopContractAddress))
to create contract. Please tell me how to an Address object call a method without ABI. I've tried but occur an error ("Not found").

**Comment by v57** [comment]
You don't need abi and Web3Contract to call the function. You can call it by knowing only its interface. Here is the guide:
https://bankex.github.io/web3swift/calling-custom-methods.html

If this function checks for msg.sender, maybe you need to provide it using:
```
let address = Address(apvShopContractAddress)
var options = Web3Options.default
options.from = sender
do {
let response = try address.call("getListItems()", web3: strongSelf.web3, options: options).wait()
    print(response.data.hex)
} catch { 
    print(error.localizedDescription)
}
```

**Comment by chymse67** [comment]
> You don't need abi and Web3Contract to call the function. You can call it by knowing only its interface. Here is the guide:
> https://bankex.github.io/web3swift/calling-custom-methods.html
> 
> If this function checks for msg.sender, maybe you need to provide it using:
> 
> ```
> let address = Address(apvShopContractAddress)
> var options = Web3Options.default
> options.from = sender
> do {
> let response = try address.call("getListItems()", web3: strongSelf.web3, options: options).wait()
>     print(response.data.hex)
> } catch { 
>     print(error.localizedDescription)
> }
> ```

Thanks for your support. Here is result:
`0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000028000000000000000000000000000000000000000000000000000000000000004600000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000082000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000009c31522ef7c89385ca1234efc1157dad6c2d66f50000000000000000000000000000000000000000000000000000000000000007486f6c6964617900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003e687474703a2f2f33352e3232302e3233372e31342f77702d636f6e74656e742f75706c6f6164732f323031392f30312f686f6c696461794032782e706e670000000000000000000000000000000000000000000000000000000000000000000e4e676179206e676869207068657000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000009c31522ef7c89385ca1234efc1157dad6c2d66f5000000000000000000000000000000000000000000000000000000000000000d43696e656d61205469636b657400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003d687474703a2f2f33352e3232302e3233372e31342f77702d636f6e74656e742f75706c6f6164732f323031392f30312f63696e656d614032782e706e67000000000000000000000000000000000000000000000000000000000000000000000b56652078656d207068696d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000009c31522ef7c89385ca1234efc1157dad6c2d66f5000000000000000000000000000000000000000000000000000000000000000e4d617373616765205469636b6574000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003b687474703a2f2f33352e3232302e3233372e31342f77702d636f6e74656e742f75706c6f6164732f323031392f30312f626f6f6b4032782e706e670000000000000000000000000000000000000000000000000000000000000000000000000a5665204d6173736167650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000009c31522ef7c89385ca1234efc1157dad6c2d66f50000000000000000000000000000000000000000000000000000000000000004426f6f6b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003b687474703a2f2f33352e3232302e3233372e31342f77702d636f6e74656e742f75706c6f6164732f323031392f30312f626f6f6b4032782e706e6700000000000000000000000000000000000000000000000000000000000000000000000004536163680000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000009c31522ef7c89385ca1234efc1157dad6c2d66f5000000000000000000000000000000000000000000000000000000000000000f486967686c616e6420436f666665650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003f687474703a2f2f33352e3232302e3233372e31342f77702d636f6e74656e742f75706c6f6164732f323031392f30312f686967686c616e644032782e706e670000000000000000000000000000000000000000000000000000000000000000184d6f74207461636820486967686c616e6420436f666665650000000000000000
`

**Comment by chymse67** [comment]
My contract address is: 0x70b3ca0150bbba1d1da88e43a44f99cfc8b64946 (Ropsten test net)
Im convert response to  an array, number of items is true but all item is empty
`         let response = try address.call("getListItems()", web3: strongSelf.web3, options: options).wait()
                    print(response.data.hex)
                    let arr = try response.array(builder: { (reader) in
                        print("\(reader)")
                    })
                    print("\(arr)")`

() [0] = {}
() [1] = {}
() [2] = {}
() [3] = {}
() [4] = {}

**Comment by v57** [comment]
Here i made some parser for your case:
```
let response = try address.call("getListItems()", web3: strongSelf.web3, options: options).wait()
try! response.pointer {
    let count = try response.intCount()
    response.headerSize = response.position
    for i in 0..<count {
        try! response.pointer {
            let header = response.headerSize
            response.headerSize = response.position
            defer { response.headerSize = header }
            let a = try! response.uint16()
            let b = try! response.string()
            let c = try! response.string()
            let d = try! response.string()
            let e = try! response.uint16()
            let f = try! response.uint32()
            let g = try! response.bool()
            let h = try! response.address()
            print(a,b,c,d,e,f,g,h)
        }
    }
}
```

**Comment by chymse67** [comment]
 Thank you very much, my issue got resolved.
