### ISSUE TITLE
Invalid method signature

### ISSUE THREAD

**Issue by mtynior** [BANKEX/web3swift#298]
In a contract, I have a public property called `index`.

In the iOS app, I try to get this value using the following code:
```
let web3 =  Web3(url: URL(string: "server adress")!)!
let abi = "Full ABI goes here"
let cotractAddress = "0x....."
let contract = try! web3.contract(abi, at: contractAddress)
let response = try! contract.method("index", options: nil).callPromise().wait()
```

When I run this code, I get `web3swift.Web3Error.processingError("Can not decode returned parameters")` error.

To find the reason for this issue I've compared request sent from `web3swift` with the request sent by the javascript version of web3. It turned out that requests had different method signatures.

Method signature for `web3swift` was `0xdfcbe054` where for `web3 js` it was `0x2986c0e5`. 

I've checked online [tool](https://emn178.github.io/online-tools/keccak_256.html) for `index()` and it generates the same hash as `web3 js` - `0x2986c0e5`.

It looks like that `ABIv2.Element.Function.methodEncoding` is returning incorrect value. 
Or to be more precise, the `keccak256()` is generating the wrong hash,  as the input data for hashing `ABIv2.Element.Function.signature` is valid.

What's interesting, the `keccak256()` is generating a proper hash for longer method names e.g: `voteForCandidate()`.

**Additional information**
web3swift version: 2.1.10
iOS: 12.2
Xcode: 10.2.1

I think this is not necessary for this issue, but, just in case, here is the definition of index property from ABI (rest of the ABI is removed for brevity):
```
{
  "constant": true,
  "inputs": [],
  "name": "index",
  "outputs": [
    {
      "name": "",
      "type": "uint256"
    }
  ],
  "payable": false,
  "stateMutability": "view",
  "type": "function"
}
```

**Comment by skywinder** [comment]
We moved our development to the new repo
➡️https://github.com/matterinc/web3swift ⬅️ 
Feel free continue discussion in the new repository. 👍

**Comment by mtynior** [comment]
The library from [new repo](https://github.com/matterinc/web3swift) is working.

**Comment by skywinder** [comment]
@mtynior thanks for mention it. 👍 

cc @v57
