### ISSUE TITLE
Support Infura V3

### ISSUE THREAD

**Issue by romain64** [BANKEX/web3swift#301]
Infura no longer supports the old API, now we have to access through **https://mainnet.infura.io/v3/<PROJECT_ID>**

I updated Web3+Infura.swift accordingly with /v3/ and now pass my Infura Project ID to the  `InfuraMainnetWeb3(<Project ID>)` function.

**Web3.swift** _(unchanged)_
```
public static func InfuraMainnetWeb3(accessToken: String? = nil) -> web3 {
        let infura = InfuraProvider(Networks.Mainnet, accessToken: accessToken)!
        return web3(provider: infura)
    }
```

**Web3+Infura.swift**
```
public class InfuraProvider: Web3HttpProvider {
    public init?(_ net:Networks, accessToken token: String? = nil, keystoreManager manager: KeystoreManager? = nil) {
        var requestURLstring = "https://" + net.name + ".infura.io/v3/"
        if token != nil {
            requestURLstring = requestURLstring + token!
        }
        let providerURL = URL(string: requestURLstring)
        super.init(providerURL!, network: net, keystoreManager: manager)
    }
...
}
```
Each call now throws the following error. 

```
EtherWalletTest[3957:62791] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "Project ID is required in the URL";
    srvr = "mainnet.infura.io";
    sync = syna;
}
```

It seems that the project ID is missing in the call, but printing requestURLstring shows the correct URL with the access token.

**Comment by skywinder** [comment]
We moved our development to the new repo
➡️https://github.com/matterinc/web3swift ⬅️ 
Feel free continue discussion in the new repository. 👍

**Comment by BaldyAsh** [comment]
@romain64 hi. I've fixed this problem in the new repo, link to which provided by @skywinder. Seems that this repo isn't supported by Bankex team, but the new repo is completely supported by the original web3swift team. So don't be afraid to use it ;)

**Comment by skywinder** [comment]
Thanks, @BaldyAsh here is a ref: https://github.com/matter-labs/web3swift/commit/363955fe8bf42649acd0618e2af1940738a49af4

**Comment by romain64** [comment]
Thanks! Closing the issue
