### ISSUE TITLE
How to get public key After generating a wallet?

### ISSUE THREAD

**Issue by amirhossein7** [BANKEX/web3swift#309]

**Comment by skywinder** [comment]
This repo is outdated and not supported anymore. Core contributors moved development to the new repo:
https://github.com/matter-labs/web3swift
Feel free continue discussion in the new repository.

**Comment by amirhossein7** [comment]
> This repo is outdated and not supported anymore. Core contributors moved development to the new repo:
> https://github.com/matter-labs/web3swift
> Feel free continue discussion in the new repository.

ok **thanks**
