### ISSUE TITLE
how to use the method in contract?

### ISSUE THREAD

**Issue by wufeiafei** [BANKEX/web3swift#35]
hi, how to use the method I set in the  contract?

for example:
   
![1522835973304](https://user-images.githubusercontent.com/3910941/38301451-25853576-3832-11e8-8bb1-bb0ca2c69f96.jpg)

how can I use "greet" in contract by web3?

**Comment by shamatar** [comment]
Hello @wufeiafei 

You should use a method "func testInfuraERC20name()" from the web3swift tests as an example. Constant and mutating functions are supported at the moment, but not constructors (yet).

Sincerely, Alex
