### ISSUE TITLE
Creating a new keystore using mnemonics

### ISSUE THREAD

**Issue by SanderKleykens** [BANKEX/web3swift#4]
I've been trying to generate a mnemonic and use that mnemonic to initialise a keystore.
The code:

```
let mnemonic = try! BIP39.generateMnemonics(bitsOfEntropy: 256)!
let keystore = try! BIP32Keystore(mnemonics: mnemonic, password: "", mnemonicsPassword: "")
```

Nothing too special, right?
I must be missing something, because I'm getting a "Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: web3swift.AbstractKeystoreError.keyDerivationError" error on the second line.

This error originates from BIP32Keystore#createNewAccount on line 121 ("guard let newAddress = Web3.Utils.publicToAddress ..."). Apparently Web3.Utils#publicToAddressData returns nil "if (stipped.count != 64)" and line 121 in BIP32Keystore#createNewAccount throws a keyDerivationError when this is the case.

Am I misusing the API or is this a bug?

Thanks in advance!

**Comment by shamatar** [comment]
It's a bug indeed (forgot to decompress a public key), I've pushed version 0.2.10 with a fix. Although I highly recommend you to test keystore creating and derived addresses on some known input (either reference values from BIP39 and BIP32, or your own mnemonics) until I add some tests for it

**Comment by SanderKleykens** [comment]
Thanks @shamatar, that seems to have helped indeed :)

If I can find the time to continue work on my project I’ll see if I can help write some tests for this.

Thanks for the library, by the way!
