### ISSUE TITLE
Mnemonic account with five level derivation path like M/44'/60'/0'/0/1

### ISSUE THREAD

**Issue by MobDeveloper163** [BANKEX/web3swift#42]

**Comment by shamatar** [comment]
fyi @skywinder

**Comment by shamatar** [comment]
Fixed in master, #44

**Comment by shamatar** [comment]
Feel free to reopen if necessary.

**Comment by MobDeveloper163** [comment]
@shamatar I just did what you said, It's still working. I got the `error.encryptionError:
"Derivation depth mismatch` error. 
Here is my code:
```
try BIP32Keystore(mnemonics: mnemonic, password: password, mnemonicsPassword: "", language: .english, prefixPath: "m/44'/60'/0'/0/0")
```

**Comment by shamatar** [comment]
Would you reopen an issue in this case?

________________________________

**Comment by MobDeveloper163** [comment]
As the problem has not been solved, I'd like to reopen it.

**Comment by shamatar** [comment]
Would you try again after refresh from master, new tests in #74 succeed for your case.

**Comment by shamatar** [comment]
@MobDeveloper163 

Ryan, did you test a latest version?

**Comment by MobDeveloper163** [comment]
Helped a lot. thank you
