### ISSUE TITLE
I can not use my contract ?

### ISSUE THREAD

**Issue by wufeiafei** [BANKEX/web3swift#43]
hi,
my contract is here:
![image](https://user-images.githubusercontent.com/3910941/38466203-162bab54-3b58-11e8-94a7-20ead1c5c5f9.png)

but, when I use web3wift, the contract is not work.
this is my code:
![1523182536695](https://user-images.githubusercontent.com/3910941/38466251-019e2260-3b59-11e8-954b-fe07cc6b6d3f.jpg)
![1523196595604](https://user-images.githubusercontent.com/3910941/38468507-a7fcb214-3b79-11e8-9f37-b6d255aa6cd8.jpg)

I use the method"setFlagData" and "getFlagData", but no work.

the result like this:
the "setFlagData" result:
res:
.success([:])
and the "getFlagData" result:
get res:
.success(["0": ""])

what can I do?

**Comment by shamatar** [comment]
Hello @wufeiafei 

Are you sure that "getFlagData" method doesn't return an empty string for this msg.sender? If it does, than your result is correct, you get a default (empty) value.

Regarding the "setFlagData" result: .success([:]) is a valid response if you "call" this method, since it returns nothing in your contract code. To send a transaction and mutate a state your should use a send() method of transaction intermediate

Sincerely, Alex

**Comment by wufeiafei** [comment]
the "getFlagData" method return:    .success(["0": ""])
I think the result should be "hello", when I used "setFlagData" method input.
but not get.

**Comment by shamatar** [comment]
Can you use the latest version (0.4.1) and check the logs. When returned information is decoded there are log messages, it will help to trace a problem

________________________________

**Comment by wufeiafei** [comment]
hi, when I use the latest version (0.4.1),
the "setFlagData" method log message is:
![1523238415923](https://user-images.githubusercontent.com/3910941/38475506-422b9ff6-3bdb-11e8-811e-0f1eac7e9aa8.jpg)

and the "getFlagData" method log message is : 
![1523238448698](https://user-images.githubusercontent.com/3910941/38475521-56d4bdc0-3bdb-11e8-8014-da72d56ad675.jpg)

what is mistake？

**Comment by shamatar** [comment]
Hello @wufeiafei 

I've created a similar contract 
```
pragma solidity ^0.4.21;


contract Whisper {
    
    struct Friend {
        string flagData;
    }
    
    mapping (address => Friend) friends;
    
    function setFlagData(string data) public {
        friends[0].flagData = data;
    }
    
    function getFlagData() public view returns (string data) {
        return friends[0].flagData;
    }
    
}
```

and submitted some data to it using remix. Here is my response:
```
["0": testData, "data": testData]
```

You can find a code in test cases in developer branch, function 
```
func testUserCase()
```

**Comment by wufeiafei** [comment]
yes, I test your code and get the"getFlagData" response like that: ["0": testData, "data": testData],when I submitted some data to it using remix.
But ,if I use "setFlagData" method by web3swift in iOS , the "setFlagData" method response is :
 string
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000046874747000000000000000000000000000000000000000000000000000000000
Full data: 

.success([:])

then, I use "getFlagData", the response is the old, not the new.

this is my code:
![1523271638574](https://user-images.githubusercontent.com/3910941/38494380-5411fb3c-3c28-11e8-91dd-9624418708e6.jpg)

**Comment by shamatar** [comment]
You use mutating (not “view” and not “pure”) method “setFlagData”, so when you “call” it - you do not send a transaction, but try to call a function that returns nothing (“returns ()”).

You should instead use send() method on intermediate and that a transaction will go into network and change a value in your contract

________________________________

**Comment by wufeiafei** [comment]
hi, I instead use send() method on intermediate, 
![1523274591548](https://user-images.githubusercontent.com/3910941/38496204-3255434e-3c2f-11e8-8954-af2038ed3b4c.jpg)

but the result is fail.

string
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000968656c6c6f576562330000000000000000000000000000000000000000000000
Transaction
Nonce: 1
Gas price: 5000000000
Gas limit: 90000
To: 0xb6b34A03045D8Aa0D210788881bffEc10c4f166e
Value: 0
Data: 0xa46b5b6b0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000968656c6c6f576562330000000000000000000000000000000000000000000000
v: 1
r: 0
s: 0
Intrinsic chainID: Optional(95518)
Infered chainID: Optional(1)
sender: nil
hash: Optional("0xe1719833c6cc8ccca0af6e24a0be8cbdc93aeefbd17237d56bfc217705e5e777")

set result
.failure(transactionSerializationError)
transactionSerializationError

**Comment by shamatar** [comment]
I've found a bug in sending an unsigned transaction to external node. Fixed in #44

**Comment by wufeiafei** [comment]
hi， when I use the lastst code by pod 'web3swift', git: 'https://github.com/BANKEX/web3swift.git',:commit =>'782d5ee'  ,
show the  erros like this:
![1523328664984](https://user-images.githubusercontent.com/3910941/38533752-52f0291a-3cad-11e8-8e23-d499a79e9103.jpg)

what can I do?

**Comment by wufeiafei** [comment]
hi,
I use the lastest code version 0.5.0.
but the use  "setFlagData" method in contract, the result also is bad.
![1523425045711](https://user-images.githubusercontent.com/3910941/38598148-d49b11a6-3d8d-11e8-8ad1-57c0e9bab092.jpg)

the log and result is : 

sender:
EthereumAddress(_address: "0x696e2405d2c914228e4409307372aacb470ad833")
Signature required 3 rounds
Transaction
Nonce: 0
Gas price: 5000000000
Gas limit: 90000
To: 0xb6b34A03045D8Aa0D210788881bffEc10c4f166e
Value: 0
Data: 0xa46b5b6b0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000968656c6c6f576562330000000000000000000000000000000000000000000000
v: 191071
r: 115484963803047457941187315055774630604535195829756633299156415369938984242572
s: 5606618538296490632424069479196750027399791712033427709004373420558424659314
Intrinsic chainID: Optional(95518)
Infered chainID: Optional(95518)
sender: Optional("0x696e2405d2C914228E4409307372aACb470aD833")
hash: Optional("0xe8677fee1e5c800b478330c2de6980daf28776a519e5eff1c941c66f94e5d67c")

Transaction
Nonce: 0
Gas price: 5000000000
Gas limit: 90000
To: 0xb6b34A03045D8Aa0D210788881bffEc10c4f166e
Value: 0
Data: 0xa46b5b6b0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000968656c6c6f576562330000000000000000000000000000000000000000000000
v: 191071
r: 115484963803047457941187315055774630604535195829756633299156415369938984242572
s: 5606618538296490632424069479196750027399791712033427709004373420558424659314
Intrinsic chainID: Optional(95518)
Infered chainID: Optional(95518)
sender: Optional("0x696e2405d2C914228E4409307372aACb470aD833")
hash: Optional("0xe8677fee1e5c800b478330c2de6980daf28776a519e5eff1c941c66f94e5d67c")

set result
.failure(nodeError("invalid sender"))
nodeError("invalid sender")



can you help me check it?

**Comment by shamatar** [comment]
Are you using a parity node? Looks like a node doesn’t like EIP155 standard and can not check a signature with a high ChainID. Try to set web3.provider.network = nil and run the same code

________________________________

**Comment by wufeiafei** [comment]
hi, 
I added "web3.provider.network = nil " to code,but has errior：Cannot assign to property: '' is a get-only property。
![1523436248529](https://user-images.githubusercontent.com/3910941/38606158-da74b2ca-3da7-11e8-8ca7-360cbdaba72a.jpg)

I see the code in Web3+Protocols.swift：
![1523436291751](https://user-images.githubusercontent.com/3910941/38606223-05e60dd2-3da8-11e8-8d49-99bff5d05991.jpg)
so can not set web3.provider.network = nil

**Comment by shamatar** [comment]
Can you test agains the latest master, after #48 you can set a network to nil

**Comment by skywinder** [comment]
@wufeiafei Fixed by #48 
Feel free to reopen the issue, if you still need help. 👍

**Comment by trnhgquan** [comment]
i have a question: I already have SmartContract in Solidity, how can i get contract ABI in json?

**Comment by shamatar** [comment]
If you use Remix, it’s in details on the first tab, near the “compile” button
