### ISSUE TITLE
Web3 Provider

### ISSUE THREAD

**Issue by CrisESC93** [BANKEX/web3swift#5]
Hello!

I try to use another provider than Infura like my own node installed in my mac (localhost) or any other into my LAN but always returns nil.

I see this [issue](https://github.com/BANKEX/web3swift/issues/1) and I tried to configure the provider using the lastest version of web3swift at today (0.2.10).

I hope can help me.

Anyway, thanks for create this awesome library.

**Comment by shamatar** [comment]
Hello Cris.

I've pushed a fix in 0.2.11, would you check it. Also, don't forget to disable app transport security if you connect to localhost by http.

Sincerely, Alexander

**Comment by CrisESC93** [comment]
Works great, thanks @shamatar !!!
