### ISSUE TITLE
Signing and unsigning.

### ISSUE THREAD

**Issue by gkd720** [BANKEX/web3swift#52]
I was doing some experimentation in developing an application that used the public ethereum blockchain, and accessing with web3.js. I poked around in this repository, looking for some specific web3.js functions, like "sign" and "ecrecover", but I didn't see them. I do see a "sign" method associated with transactions, however. I want to be able to sign a user generated string/data, and then later recover the signer from a signature. I was using web3.eth.personal.sign and web3.eth.personal.ecRecover. Are similar functions available in this package? Thanks.

**Comment by shamatar** [comment]
Hello @gkd720 

All functions you mentioned are used under the hood, but most likely not exposed as a part of public API. I'll expose them in the next minor version, thank you for spotting this problem.

Sincerely, Alex

**Comment by shamatar** [comment]
Implemented and released in 0.5.2. Please have a look and reopen if necessary.

Sincerely, Alex
