### ISSUE TITLE
Signing identical transaction results in different raw tx

### ISSUE THREAD

**Issue by ashchan** [BANKEX/web3swift#53]
When creating `EthereumTransaction` multiple times (all data including `nonce` are identical) and signing with the same private key, it gets different raw tx(rlped tx) with `EthereumTransaction.encode(forSignature: false)`. Is this expected behavior?

Looks like `r` and `s` from secp256k1 are changing each time.

**Comment by shamatar** [comment]
Hello @ashchan 

It's indeed an expected behavior. Secp256k1 library from Bitcoin allows to supply an additional entropy when signing, and it's utilized by web3swift. In addition, an explicit public key recovery from the signature is done to ensure that recovered signer key matches the private key.

Sincerely, Alex

**Comment by ashchan** [comment]
@shamatar 

Thanks for responding quickly.

I looked at the Secp256k1 wrapper and found that it indeed uses a random entropy while calling `secp256k1_ecdsa_sign_recoverable`. (go-ethereum and other libraries don't seem to do so).

Closing this. Thank you.

**Comment by shamatar** [comment]
@ashchan 

Yes, TX hash can change, but nevertheless it's completely determined by the content and signature and can not change after being signed and sent, so identifier after a successfully sending it will stay. I'm not aware of any case when knowledge of completely deterministic signature is required before production of the signature (you can not get it without a private key anyway), but if you do - please post here.

Sincerely, Alex

**Comment by shamatar** [comment]
@ashchan 

I've added an extra test for deterministic (without extra entropy) signature, although it fails in 50% cases in simulator and on iOS device. 

Sincerely, Alex

**Comment by shamatar** [comment]
I've found an error that made a signature fail 50% of time without extra entropy. Now deterministic signatures work and I can set them as defaults if necessary, although having some extra entropy is usually a good option.

**Comment by ashchan** [comment]
@shamatar Awesome! Just did some tests, now Ethereum transaction sign is consistent. Aldo checked that with MEW and they produce the same raw tx for the same transaction.

Thank you!
