### ISSUE TITLE
the method " web3.eth.getBlockByNumber()" reseult  fail?

### ISSUE THREAD

**Issue by wufeiafei** [BANKEX/web3swift#54]
Hi,
 I use the method " web3.eth.getBlockByNumber()" ,but the result is failture.
this is my code : 
let web3 = Web3.new(URL.init(string: "http://127.0.0.1:8545")!)!
let response = web3.eth.getBlockByNumber(UInt64(2614), fullTransactions: false)

and the reponse result is : 
.failure(nodeError("invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type common.Hash"))

===
what can I do?

**Comment by shamatar** [comment]
fixed in #55
