### ISSUE TITLE
I use contract verify signature, but the address is not correct?

### ISSUE THREAD

**Issue by wufeiafei** [BANKEX/web3swift#63]
hi,
I use web3swift method "Web3Signer.signPersonalMessage" make a signature, then I use the contract method "validate", but the result is not correct, the address is different with  the signature address.
this  is my contract:

pragma solidity ^0.4.17;

contract BBQ {
    
  //验签数据入口函数
    function validate(uint8 v,bytes32 r,bytes32 s,uint number) view returns (address,bool){

        string memory message = uint2str(number);
        string memory lengths = uint2str(bytes(message).length);
        string memory prefix = strConcat("\u0019Ethereum Signed Message:\n",lengths);
        bytes32 data = sha3(bytes(prefix),bytes(uint2str(number)));
        bytes32 prefixedHash = sha3(data);
        address endecodedAddress = ecrecover(prefixedHash, v, r, s);

        return (endecodedAddress,msg.sender == endecodedAddress);
    }
    
    function uint2str(uint i) internal pure returns (string){
        if (i == 0) return "0";
        uint j = i;
        uint length;
        
        while (j != 0){
            length++;
            j /= 10;
        }
        
        bytes memory bstr = new bytes(length);
        uint k = length - 1;
        
        while (i != 0){
            bstr[k--] = byte(48 + i % 10);
            i /= 10;
        }
        return string(bstr);
    }
    
    // 连接两个string
    function strConcat(string _a, string _b) internal returns (string){
        bytes memory _ba = bytes(_a);
        bytes memory _bb = bytes(_b);

        string memory abcde = new string(_ba.length + _bb.length);
        bytes memory babcde = bytes(abcde);
        uint k = 0;
        for (uint i = 0; i < _ba.length; i++) babcde[k++] = _ba[i];
        for (i = 0; i < _bb.length; i++) babcde[k++] = _bb[i];

        return string(babcde);
    }
    
}

and this is my swift code:

![1524043221014](https://user-images.githubusercontent.com/3910941/38923341-e15fcf22-432c-11e8-835b-ac635a0b874a.jpg)
![1524043249556](https://user-images.githubusercontent.com/3910941/38923353-e6850cc4-432c-11e8-96ed-e6355752ea97.jpg)

======
pls, help me check it?

**Comment by shamatar** [comment]
I’ve pushed a test into “developer” branch, it gives an idea of how to get a signature, get V, R, S from it and test it locally. I’ve also separately tested it with ethereumjs-util and got the same result

**Comment by shamatar** [comment]
I expect to also deploy a contract on Rinkeby to cross-verify it

**Comment by shamatar** [comment]
Hello @wufeiafei 

I've tested everything, it worked as expected.

Here is a solidity contract for ECRecover 

```
pragma solidity ^0.4.19;

import {Conversion} from "./Conversion.sol";

contract ECRecover {
    using Conversion for uint256;
    bytes constant PersonalMessagePrefixBytes = "\x19Ethereum Signed Message:\n";
  
  constructor() public {
      
  }
  
  function hashPersonalMessage(string _message) public pure returns (bytes32 hash) {
      uint256 length = bytes(_message).length;
      hash = keccak256(PersonalMessagePrefixBytes, length.uintToBytes(), _message);
      return hash;
  }
  
  function recoverSigner(string _message, uint8 v, bytes32 r, bytes32 s) public pure returns (address signer) {
      bytes32 hash = hashPersonalMessage(_message);
      if (v < 27) {
          v = v + 27;
      }
      signer = ecrecover(hash, v, r, s);
      return signer;
  }
}

pragma solidity ^0.4.20;

library Conversion {

    function uintToBytes(uint256 self) internal pure returns (bytes memory s) {
        uint maxlength = 100;
        bytes memory reversed = new bytes(maxlength);
        uint256 i = 0;
        while (self != 0) {
            uint256 remainder = self % 10;
            self = self / 10;
            reversed[i++] = byte(48 + remainder);
        }
        s = new bytes(i);
        for (uint256 j = 0; j < i; j++) {
            s[j] = reversed[i - 1 - j];
        }
        return s;
    }
}
```

In test you can also find an example of how to properly parse a signature and pass it to the contract in the 
```
func testPersonalSignatureOnContract()
```
Merged in #66 

Sincerely, Alex

**Comment by wufeiafei** [comment]
hi, I use method "SECP256K1.unmarshalSignature()", show the error "Use of unresolved identifier 'SECP256K1'".
And I has import import web3swift、BigInt、Result、secp256k1_ios and CryptoSwift。

![1524102675998](https://user-images.githubusercontent.com/3910941/38966969-74f974ec-43b7-11e8-929c-433b24df6295.jpg)
![1524102769146](https://user-images.githubusercontent.com/3910941/38966971-76af7d86-43b7-11e8-9f3f-1ae77a312d4a.jpg)

==== 
what can I do?

**Comment by shamatar** [comment]
Hello @wufeiafei 

I've exposed function unmarshalSignature and marshalSignature as a part of Web3.Utils.

**Comment by wufeiafei** [comment]
I test your exapmle, the result is ok。
Then I deploy your solidity contract for ECRecover in my private chain， the result is not ok。 I can not get the same address.

**Comment by wufeiafei** [comment]
Thank you very much.
I konw the reseason why the address is different.
the contract signature use hash 2 times, but web3swift hash only one time.
I has add the method "signPersonalMessage2Hash" and "personalECRecover2Hash", and pull requests.
