### ISSUE TITLE
I use event,but the EventParsingResult is empty?

### ISSUE THREAD

**Issue by wufeiafei** [BANKEX/web3swift#64]
hi,
I use the event, ,but the EventParsingResult is empty.
the contract is : 

pragma solidity ^0.4.0;

contract ClientReceipt {
    
    event Deposit(
        address indexed _from,
        string     _id,
        uint indexed _value
    );

    function deposit(string _id) public  payable {

       emit Deposit(msg.sender, _id, msg.value);
    }
    
}

this is my code:
![1524045933635](https://user-images.githubusercontent.com/3910941/38925841-54059484-4333-11e8-979c-b8cb0bb454fc.jpg)

====
pls, help me check it?

**Comment by shamatar** [comment]
Would you instead follow an example as in function “testEventParsing2usingABIv2” in tests? It’s much shorter and easier to use.

**Comment by shamatar** [comment]
#67 has an example in tests for your case, I've tested it on Rinkeby. Function
```
func testUserCaseEventParsing()
```

**Comment by wufeiafei** [comment]
I test that  it  work good . thank you very much.
