### ISSUE TITLE
BIP39 Keystore not accessible from keystore parameter path

### ISSUE THREAD

**Issue by pandeyshivang** [BANKEX/web3swift#68]
let userDir = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]
      
   
         let ks = KeystoreManager.managerForPath(userDir + "/keystore")
        self.keystoreManager = ks
        web3rinky?.addKeystoreManager(ks)
      
        address = ks?.addresses?[0].address
crash when getting address from keystoremanager.
Error in latest version in CryptoSwift?

**Comment by shamatar** [comment]
Did you previously create a BIP32 keystore and save it to that directory? Just in case

**Comment by pandeyshivang** [comment]
yeah i want to create hd wallet
  let mnemonic = try! BIP39.generateMnemonics(bitsOfEntropy: 256)!
                        let keystore = try! BIP32Keystore(mnemonics: mnemonic, password: password, mnemonicsPassword: "")
                        let keydata = try JSONEncoder().encode(ks?.keystoreParams)
                        FileManager.default.createFile(atPath: userDir + "/keystore"+"/key.json", contents: keydata, attributes: nil)

**Comment by pandeyshivang** [comment]
@shamatar  I have just solved it...

 let data = try Data(contentsOf: URL(fileURLWithPath: path), options: .mappedIfSafe)
  let jsonResult = try JSONSerialization.jsonObject(with: data, options: .mutableLeaves)
  let bip32keystore = BIP32Keystore.init(data)
```

**Comment by shamatar** [comment]
Oh, I didn’t understand a question. Yes, you can either create a keystore from phrase and lib will save a necessary information to JSON that you can write to disk, or you can supply either Json string or data to recreate it from saved copy.

**Comment by shamatar** [comment]
Please keep in mind that BIP 32 keystore JSON format is not standartized, so files are not compatible with other libs. For BIP32KEYSTORE keystore everyone just backups a seed phrase, it’s enough. Be sure to allow your users to backup a seed phrase after creation and destroy it after

**Comment by pandeyshivang** [comment]
@shamatar but connectionError in Send ether.

**Comment by shamatar** [comment]
Please check your internet connection (if using Infura) or connection to the local node. If you are using Geth be sure to have —rpc flag and —rpccors if necessary

________________________________

**Comment by pandeyshivang** [comment]
my internet is working fine and i am using infura and whenever i send i got invalid address.

**Comment by shamatar** [comment]
Would you try a latest commit in master?

________________________________

**Comment by pandeyshivang** [comment]
@shamatar  yeah i installed latest version of web3swift. my code is send ether in bip32keystore...

` let contract = self.web3rinky?.contract(Web3.Utils.coldWalletABI, at: toaddress)
                        var options = Web3Options.defaultOptions()
                        options.value = Web3.Utils.parseToBigUInt(amount, units: .eth)
                        options.from = self.bip32keystore?.addresses?.first
                        let intermediate = contract?.method("fallback", options: options)
                        let result = intermediate?.send(password: pass)

                        let realert = UIAlertController(title: "Result is :", message: String(describing: result), preferredStyle: .actionSheet)
`

**Comment by pandeyshivang** [comment]
@shamatar Yeah it works in 0.5.6 version...
