### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by trnhgquan** [BANKEX/web3swift#75]
Hi ,

I just create new project ( i am using Xcode 9.2 and Swift 4.0.3). 
Pod init and insert pod 'web3swift', :git => 'https://github.com/bankex/web3swift.git' . After that, i ran pod install and it successfully but when i open myproject.xcworkspace. I got 25 error and framework in red color. What wrong ? Does anyone here got the same issue can help me?
You can check my podfile and my project after pod install via link:
1.https://uphinhnhanh.com/image/zGV5pC
2.https://uphinhnhanh.com/image/zGVkp4

**Comment by pandeyshivang** [comment]
@trnhgquan  update xcode 9.3 because cryptoswift lib require swift 4.1 version and xcode 9.2 dost not  support swift version....

**Comment by shamatar** [comment]
Yes, I shall bump a required version in a podspec, XCode9.3 works out of the box

________________________________

**Comment by shamatar** [comment]
Version 0.6.0 requires Swift 4.1 and you should get a proper warning when installing
