### ISSUE TITLE
Feature requests needed

### ISSUE THREAD

**Issue by shamatar** [BANKEX/web3swift#84]
Hello guys.

As the main part of the lib is complete, I’m now accepting feature requests. Ideally those should be something more than just a convenience methods. After the release of Bankex implementation of confidential voting and transactions, as well as Plasma the lib will bring in some heavy crypto for SNARK verification and other features. In a meantime I can focus on more mainstream features. 

Sincerely, Alex

**Comment by ToToDoDo** [comment]
I wish to have an easy way to decode the input data of Tx and logs from Tx Receipt by ABI like this library. Then I can use it to get transfer amount of ERC20 token from Tx.
https://github.com/ConsenSys/abi-decoder

**Comment by ToToDoDo** [comment]
May be it's not what web3 library should do but I want get token summary like "name", "symbol", "Total Supply" and "Decimals" by an address of contract.

**Comment by shamatar** [comment]
In this case please refer to various tests and an Example. There you can find how to read various token parameters by calling an appropriate function. There is definitely an example of ERC20 token “name” field.

Sincerely, Alex

________________________________

**Comment by shamatar** [comment]
Hello @pandeyshivang 

Thanks for an excellent overview 👍

**Comment by skywinder** [comment]
Hello. Me and Alex (@shamatar) as main maintainers are moving our development to the new repo.
➡️https://github.com/matterinc/web3swift ⬅️ 
Feel free continue discussion in the new repository. 👍 
Cheers.

**Comment by skywinder** [comment]
This issue was moved to matterinc/web3swift#90
