### ISSUE TITLE
How can i import a privatekey which has 64 length?

### ISSUE THREAD

**Issue by jopinfly** [BANKEX/web3swift#85]
Hello guys,
  i try to generate a `EthereumKeystoreV3` by call `public init? (privateKey: Data, password: String = "BANKEXFOUNDATION")`，but it will return nil because length is 64. Pls tell me how to solve it~ Thx

**Comment by jopinfly** [comment]
oooh,this is a stupid question.
i used do like `EthereumKeystoreV3(privateKey: "privatekey".data(using: .ascii), password: "password")`
i changed it to `EthereumKeystoreV3(privateKey: "privatekey".hexToData(), password: "password")`
it works

**Comment by shamatar** [comment]
Hello @jopinfly, I’m glad you have figured this out.
