### ISSUE TITLE
how to attach "private note" when transfer token?

### ISSUE THREAD

**Issue by MobDeveloper163** [BANKEX/web3swift#87]
![attach](https://user-images.githubusercontent.com/23459575/39574893-432cc3ec-4f0b-11e8-9a9b-544adae08ccb.png)

As the pic showing above, the private note is empty here. I've tried to pass data to the constructor of EthereumTransaction. It does not work. So what's the right way to  attach a private note when making a transaction?

**Comment by shamatar** [comment]
Etherscan’s private note function is unrelated to the library and Ethereum in general. You can set it only on Etherscan

________________________________

**Comment by MobDeveloper163** [comment]
Thanks.
