### ISSUE TITLE
Example and Code are different

### ISSUE THREAD

**Issue by Abhishek-NickelFox** [BANKEX/web3swift#9]
In example source the code looking too old , getting address array issue in KeyStoreManager Class?
Please cross check once

**Comment by shamatar** [comment]
Yes, I don't spend much time changing an example, API is expected to be stabilized in 0.3 release planned for a next week.

Sincerely, Alexander

**Comment by shamatar** [comment]
At the moment there is a massive refactoring, when API will be stabilized we will start to work on documentation

**Comment by shamatar** [comment]
Please use tests as an example of usage
