### ISSUE TITLE
How to sign tokens?

### ISSUE THREAD

**Issue by h-js** [BANKEX/web3swift#90]

**Comment by shamatar** [comment]
An example of ERC20 tokens transfer can be found either in tests or in Example. You do not even need to supply an ABI, there is standard one in Web3.Utils struct

**Comment by skywinder** [comment]
Please, kindly check our Example.

Here is the detailed description in the readme, how to run it:
https://github.com/BANKEX/web3swift#example

Here is a code:
https://github.com/BANKEX/web3swift/tree/master/Example/web3swiftExample

There are quite straightforward steps, how to implement things, that you needed.

If you still don't find an answer to your question - feel free post the detailed description of your case.

**Comment by shamatar** [comment]
Please refer to #92
