### ISSUE TITLE
How to create and send transaction?

### ISSUE THREAD

**Issue by trnhgquan** [BANKEX/web3swift#91]
Please can you show me step by step??
I already have smartcontract on Ropsten testnest ( smAddress)
I already have an account on Ropsten testnest (accountAddress)
I want to interact with function answer(address les,uint index, string answer)  in my SM that has been deployed at smAddress.
How can i do by using web3swift to create tx and send from accountAddress??

Please help

**Comment by skywinder** [comment]
Dear @trnhgquan .

Did you check an Example in this repo?
https://github.com/BANKEX/web3swift/tree/master/Example/web3swiftExample

There are quite straightforward steps, how to implement things, that you needed.

If you still don't find an answer to your question - feel free post the detailed description of your case.

**Comment by jaramburu** [comment]
Hey there, I am also a bit confused by the token transfer example. When sending eth where exactly do you input the recipient address?

**Comment by trnhgquan** [comment]
Dearr @skywinder , many thx you guys for replying me.
I did check that example and run it but i didnt know what is (password: "BANKEXFOUNDATION") in code below:

        if (keystoreManager?.addresses?.count == 0) {
            ks = try! EthereumKeystoreV3(password: "BANKEXFOUNDATION")
            let keydata = try! JSONEncoder().encode(ks!.keystoreParams)
            FileManager.default.createFile(atPath: userDir + "/keystore"+"/key.json", contents: keydata, attributes: nil)
        } else {
            ks = keystoreManager?.walletForAddress((keystoreManager?.addresses![0])!) as! EthereumKeystoreV3
        }
        guard let sender = ks?.addresses?.first else {return}
        print(sender)

In my case: all what i want just is create raw transaction and using ethescan api to send my tx.

**Comment by shamatar** [comment]
There is no way to get what you want with just 2-3 lines of code. You can manually use available public functions to assemble a contract from ABI, get nonce, estimate gas, assemble transaction and get a hex string from it. If you just want to send ETH there is a method in web3instance.eth called “sendETH”, but you still need to use a keystore to import a private key for signing. 

Sincerely, Alex

**Comment by jaramburu** [comment]
Thanks Alex, can you please post an example showing how to send a transaction? I still don't feel it's clear how to do this in any number of lines of code using the current examples. I think there are many people interested to test your repo in their applications who would appreciate this.
