### ISSUE TITLE
How to transfer ERC20 tokens?

### ISSUE THREAD

**Issue by MobDeveloper163** [BANKEX/web3swift#92]
I have "SSS" and "ETH" tokens in my account. I have transferred "ETH" successfully to another address. But when I transfer "SSS" tokens, it always failed.
Here is my code: 
```
        let sssTokenDecimals = 8
        let sssValue = Web3Utils.parseToBigUInt("10", decimals: sssTokenDecimals)
        var options = Web3Options.defaultOptions()
        options.from = fromAddress
        options.to = toAddress
        options.value = sssValue
        let contract = web3.contract(Web3Utils.erc20ABI, at: contractAddress, abiVersion: 2)
        let intermediate = contract?.method("transfer", parameters: [toAddress, sssValue!] as [AnyObject], extraData: personalData!, options: options)

        guard let transaction = intermediate?.transaction else {
            return
        }
        let estimateGasResult = web3.eth.estimateGas(transaction, options: options)
```

`estimateGasResult `always return an error. However if I set `sssValue` to `BigUInt(0)`, it worked. I have 900 'SSS' tokens in my account now. If I want to send 10 `SSS` tokens, what the value I should give?

**Comment by shamatar** [comment]
Hello @MobDeveloper163 

What is a “PersonalData” variable? You should not send any other data than just a receiver address and the amount. I’ll check a parsing function separately, but it looks fine. Please also note that if your token is non-trivial and requires a lot of gas to transfer (more than “defaultOptions” gas), than internal check when sending a transaction will fail - this behavior is made consistent with web3js.

Sincerely, Alex

**Comment by MobDeveloper163** [comment]
I'm really confused with "amount" when send ERC20 tokens.  If I want to send 10 "SSS" token, what the value of Web3Options and the value of parameters in `contract.method` should be. I'm not sure if I have made me understood. 
Thanks for your quick reply.

**Comment by MobDeveloper163** [comment]
@shamatar 

You're absolutely right. I should not set a value that is bigger than 0 to Web3Options. 

I've struggled on this for a whole day. You saved me. Thank you so much.
