### ISSUE TITLE
How to decode input data of ERC20 token transaction?

### ISSUE THREAD

**Issue by ToToDoDo** [BANKEX/web3swift#93]
I used abi-decoder to decode and parse input data of transaction to find the transfer amount of token when I developing with Javascript.

But how to decode the input data of standard ERC20 token's transaction using web3swift?

I want to find out token transfer data like this.
<img width="831" alt="2018-05-08 18 25 15" src="https://user-images.githubusercontent.com/1905256/39749520-da4bb414-52ed-11e8-8c28-ad84411ec7c3.png">

**Comment by ToToDoDo** [comment]
@shamatar Thank you for your answer. I tried to decode input data using ABIv2Decoder, But can't get transfer amount that I want with the code bellow.
![7cd4219e289e6aee980104edc821a9b6](https://user-images.githubusercontent.com/1905256/39754783-48ad309e-52fe-11e8-9f1c-dd66acc5d1d2.jpg)

Could you show me an example how to parse out transfer amount from input data of Tx bellow?
https://etherscan.io/tx/0x4f3300460c52f139a103709d018bb65a80ed5e1bcade2846992dd061b5bc94c6

**Comment by shamatar** [comment]
Hello @ToToDoDo 

Would you try a method
```
web3rospten.contract.decodeInputData("methodName", data: bigI.transaction.data)
```

Yet untested, but should work out of the box

**Comment by shamatar** [comment]
Hello @ToToDoDo 

The latest code from "master" now has functions to decode input data with and without explicit method naming, ERC20 "Transfer" test passes. I'll close for now, feel free to reopen if necessary.

Sincerely, Alex

**Comment by ToToDoDo** [comment]
@shamatar Thank you very much!
I can parse out method name from input data, but value was not correct.
How to decode the value decode by contract.decodeInputData() ?

![df0df8fbf420a769c352e34045b8e556](https://user-images.githubusercontent.com/1905256/39854379-6b2d1a02-5462-11e8-8490-8c84c475e48b.jpg)

**Comment by shamatar** [comment]
Please update to the latest master branch version, by the structure of addresses I see you have one without an important bug fix

________________________________

**Comment by ToToDoDo** [comment]
Thank you! It works well after update to the last master branch version.
