### ISSUE TITLE
Failed to transfer tokens to some addresses

### ISSUE THREAD

**Issue by MobDeveloper163** [BANKEX/web3swift#94]
It works when I transfer 10 "SSS" tokens to the address "0x066a46470fd976e89303f501b704f73016da101e", but failed to transfer tokens to "0xCfA5DAe3936638CB8531Ab51AEEc1922Dd0873de" due to  "gas required exceeds allowance or always failing transaction". 

```
  let to = EthereumAddress("0xCfA5DAe3936638CB8531Ab51AEEc1922Dd0873de")
  let contractAddress = EthereumAddress("0x7d3e7d41da367b4fdce7cbe06502b13294deb758")
  let contract = web3.contract(Web3Utils.erc20ABI, at: contractAddress, abiVersion: 2)
  let value = web3Options.value ?? BigUInt(0)
  web3Options.value = nil
  web3Options.to = nil
  let intermediate = contract?.method("transfer", parameters: [to, value] as [AnyObject], extraData: Data(), options: web3Options)
   guard let transaction = intermediate?.transaction else {
        return
   }
   guard let signedTransactionData = web3.browserFunctionsFunctions.signTransactionWith(transaction, options: web3Options, password: password) else {
        return
    }
```

I think the address  has nothing to do with it,  however it did failed when I change the receiver address. 
That's really weird. 

I also tested this on `Imtoken`, there's no such error. What did I do wrong?

**Comment by shamatar** [comment]
You don’t need to set options value to nil, it’s zero by default. I’d suggest to set options.gasLimit = BigUInt(200000) and try again. May be the contract is non-standard and requires more gas for transaction. Also, check that you do not have pending transactions on your account, may be a duplicate nonce problem again that I remember you had before.

________________________________

**Comment by MobDeveloper163** [comment]
@shamatar Thanks again. It failed because the value I gave to gasLimit is too small.
