### ISSUE TITLE
How to send ERC20 token

### ISSUE THREAD

**Issue by jaramburu** [BANKEX/web3swift#96]
Hi, can you please post a full example (including generating keystore) of how to send an ERC20 transaction? Your current ERC20 transfer example does not appear to include a 'to' address and the ERC20 transfer test does not appear to include a contract address.

**Comment by shamatar** [comment]
Hello @jaramburu 

The latest code from "master" has a convenience method to send ERC20 tokens. Have a look in tests code for function 
```
func testTokenBalanceTransferOnMainNetUsingConvenience()
```

Feel free to reopen if you have more questions.

Sincerely, Alex

**Comment by jaramburu** [comment]
Thanks Alex. Will you update the version of web3+Eth.swift in the cocoapod to include the public function sendERC20tokensWithNaturalUnits?
