### ISSUE TITLE
AbstractKeystoreError.invalidAccountError

### ISSUE THREAD

**Issue by mashkius** [BANKEX/web3swift#97]
I am trying to create EthereumKeystoreV3 with a private key, it succeeds, but fails on transfer and gives error: generalError(web3swift.AbstractKeystoreError.invalidAccountError)

let web3 = Web3.new(URL(string: "https://ropsten.infura.io/bqc72gP3oddLa6bdSDGH")!)!
        
        let sendToAddress = EthereumAddress("0x6394b37Cf80A7358b38068f0CA4760ad49983a1B")
        let tempKeystore = try! EthereumKeystoreV3(privateKey: Data(hex: self.senderWallet!.dumpPrivateKey()))
        let keystoreManager = KeystoreManager([tempKeystore!])
        print(keystoreManager.addresses)
        web3.addKeystoreManager(keystoreManager)
        let contract = web3.contract(Web3.Utils.coldWalletABI, at: sendToAddress, abiVersion: 2)
        var options = Web3Options.defaultOptions()
        options.to = sendToAddress
        options.value = Web3.Utils.parseToBigUInt("0.03", units: .eth)
        options.from = keystoreManager.addresses?.last
        print(options)
        let intermediate = contract?.method("fallback", options: options)
        guard let result = intermediate?.send(password: "") else {return }
        print(result)
        switch result {
        case .success(_):
            return
        case .failure(let error):
            guard case .nodeError(let descr) = error else {return }
            guard descr == "insufficient funds for gas * price + value" else {return }
        }

**Comment by shamatar** [comment]
When you create a wallet there is a default password “BANKEXFOUNDATION”, but later you supply just a an empty string for it.

________________________________

**Comment by mashkius** [comment]
That's right. Succeeded now. But maybe it would be worth adding password parameter when creating EthereumKeystoreV3 from privateKey?

**Comment by shamatar** [comment]
You can add it if you specify a parameter (..., password: “”), there is just a non-empty default one.

________________________________
