### ISSUE TITLE
Is that my wallet support for BIP44 standard when i create it as follows

### ISSUE THREAD

**Issue by tiantianyuan** [BANKEX/web3swift#99]
![0c74fd28-9040-4e2b-8619-d1da53efd96f](https://user-images.githubusercontent.com/19589128/39860166-eddb9bca-546e-11e8-8df9-bac812e01f30.png)

**Comment by shamatar** [comment]
Hello @tiantianyuan 

Yes, it's a way to create a BIP32 keystore based on BIP39 mnemonics and BIP44 recommended derivation path. You don't need to set
```
keystore?.mnemonics = mnemonics
```

it's unused and will be removed in the next minor version bump.

Sincerely, Alex
